// Code generated by tools/generate-crafting-catalog; DO NOT EDIT.
// Source: local D2R 3.2.92777 cubemain.txt (description) and misc.txt (name/code).
package crafting

var recipes = [...]Recipe{
	{SourceFile: "cubemain.txt", SourceKey: "3 Standard Amethysts -> Flawless Amethyst", InputCode: "gsv", InputQuantity: 3, OutputCode: "gzv", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Flawless Amethysts -> Perfect Amethyst", InputCode: "gzv", InputQuantity: 3, OutputCode: "gpv", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Standard Rubies -> Flawless Ruby", InputCode: "gsr", InputQuantity: 3, OutputCode: "glr", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Flawless Rubies -> Perfect Ruby", InputCode: "glr", InputQuantity: 3, OutputCode: "gpr", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Standard Sapphires -> Flawless Sapphire", InputCode: "gsb", InputQuantity: 3, OutputCode: "glb", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Flawless Sapphires -> Perfect Sapphire", InputCode: "glb", InputQuantity: 3, OutputCode: "gpb", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Standard Topazes -> Flawless Topaz", InputCode: "gsy", InputQuantity: 3, OutputCode: "gly", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Flawless Topazes -> Perfect Topaz", InputCode: "gly", InputQuantity: 3, OutputCode: "gpy", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Standard Emeralds -> Flawless Emerald", InputCode: "gsg", InputQuantity: 3, OutputCode: "glg", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Flawless Emeralds -> Perfect Emerald", InputCode: "glg", InputQuantity: 3, OutputCode: "gpg", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Standard Diamonds -> Flawless Diamond", InputCode: "gsw", InputQuantity: 3, OutputCode: "glw", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Flawless Diamonds -> Perfect Diamond", InputCode: "glw", InputQuantity: 3, OutputCode: "gpw", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Standard Skulls -> Flawless Skull", InputCode: "sku", InputQuantity: 3, OutputCode: "skl", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 Flawless Skulls -> Perfect Skull", InputCode: "skl", InputQuantity: 3, OutputCode: "skz", Version: 0},
	{SourceFile: "cubemain.txt", SourceKey: "3 El Runes -> Eld Rune", InputCode: "r01", InputQuantity: 3, OutputCode: "r02", Version: 100},
	{SourceFile: "cubemain.txt", SourceKey: "3 Eld Runes -> Tir Rune", InputCode: "r02", InputQuantity: 3, OutputCode: "r03", Version: 100},
	{SourceFile: "cubemain.txt", SourceKey: "3 Tir Runes -> Nef Rune", InputCode: "r03", InputQuantity: 3, OutputCode: "r04", Version: 100},
	{SourceFile: "cubemain.txt", SourceKey: "3 Nef Runes -> Eth Rune", InputCode: "r04", InputQuantity: 3, OutputCode: "r05", Version: 100},
	{SourceFile: "cubemain.txt", SourceKey: "3 Eth Runes -> Ith Rune", InputCode: "r05", InputQuantity: 3, OutputCode: "r06", Version: 100},
	{SourceFile: "cubemain.txt", SourceKey: "3 Ith Runes -> Tal Rune", InputCode: "r06", InputQuantity: 3, OutputCode: "r07", Version: 100},
	{SourceFile: "cubemain.txt", SourceKey: "3 Tal Runes -> Ral Rune", InputCode: "r07", InputQuantity: 3, OutputCode: "r08", Version: 100},
	{SourceFile: "cubemain.txt", SourceKey: "3 Ral Runes -> Ort Rune", InputCode: "r08", InputQuantity: 3, OutputCode: "r09", Version: 100},
	{SourceFile: "cubemain.txt", SourceKey: "3 Ort Runes -> Thul Rune", InputCode: "r09", InputQuantity: 3, OutputCode: "r10", Version: 100},
}
