// Code generated from D2R 3.2.92777 local data/global/excel weapons.txt, armor.txt, misc.txt; DO NOT EDIT.
package world

var itemCatalog = map[uint32]itemCatalogEntry{
	0:   {Code: "hax", Name: "Hand Axe", Type: "axe", NormalCode: "hax", UberCode: "9ha", UltraCode: "7ha"},
	1:   {Code: "axe", Name: "Axe", Type: "axe", NormalCode: "axe", UberCode: "9ax", UltraCode: "7ax"},
	2:   {Code: "2ax", Name: "Double Axe", Type: "axe", NormalCode: "2ax", UberCode: "92a", UltraCode: "72a"},
	3:   {Code: "mpi", Name: "Military Pick", Type: "axe", NormalCode: "mpi", UberCode: "9mp", UltraCode: "7mp"},
	4:   {Code: "wax", Name: "War Axe", Type: "axe", NormalCode: "wax", UberCode: "9wa", UltraCode: "7wa"},
	5:   {Code: "lax", Name: "Large Axe", Type: "axe", NormalCode: "lax", UberCode: "9la", UltraCode: "7la"},
	6:   {Code: "bax", Name: "Broad Axe", Type: "axe", NormalCode: "bax", UberCode: "9ba", UltraCode: "7ba"},
	7:   {Code: "btx", Name: "Battle Axe", Type: "axe", NormalCode: "btx", UberCode: "9bt", UltraCode: "7bt"},
	8:   {Code: "gax", Name: "Great Axe", Type: "axe", NormalCode: "gax", UberCode: "9ga", UltraCode: "7ga"},
	9:   {Code: "gix", Name: "Giant Axe", Type: "axe", NormalCode: "gix", UberCode: "9gi", UltraCode: "7gi"},
	10:  {Code: "wnd", Name: "Wand", Type: "wand", NormalCode: "wnd", UberCode: "9wn", UltraCode: "7wn"},
	11:  {Code: "ywn", Name: "Yew Wand", Type: "wand", NormalCode: "ywn", UberCode: "9yw", UltraCode: "7yw"},
	12:  {Code: "bwn", Name: "Bone Wand", Type: "wand", NormalCode: "bwn", UberCode: "9bw", UltraCode: "7bw"},
	13:  {Code: "gwn", Name: "Grim Wand", Type: "wand", NormalCode: "gwn", UberCode: "9gw", UltraCode: "7gw"},
	14:  {Code: "clb", Name: "Club", Type: "club", NormalCode: "clb", UberCode: "9cl", UltraCode: "7cl"},
	15:  {Code: "scp", Name: "Scepter", Type: "scep", NormalCode: "scp", UberCode: "9sc", UltraCode: "7sc"},
	16:  {Code: "gsc", Name: "Grand Scepter", Type: "scep", NormalCode: "gsc", UberCode: "9qs", UltraCode: "7qs"},
	17:  {Code: "wsp", Name: "War Scepter", Type: "scep", NormalCode: "wsp", UberCode: "9ws", UltraCode: "7ws"},
	18:  {Code: "spc", Name: "Spiked Club", Type: "club", NormalCode: "spc", UberCode: "9sp", UltraCode: "7sp"},
	19:  {Code: "mac", Name: "Mace", Type: "mace", NormalCode: "mac", UberCode: "9ma", UltraCode: "7ma"},
	20:  {Code: "mst", Name: "Morning Star", Type: "mace", NormalCode: "mst", UberCode: "9mt", UltraCode: "7mt"},
	21:  {Code: "fla", Name: "Flail", Type: "mace", NormalCode: "fla", UberCode: "9fl", UltraCode: "7fl"},
	22:  {Code: "whm", Name: "War Hammer", Type: "hamm", NormalCode: "whm", UberCode: "9wh", UltraCode: "7wh"},
	23:  {Code: "mau", Name: "Maul", Type: "hamm", NormalCode: "mau", UberCode: "9m9", UltraCode: "7m7"},
	24:  {Code: "gma", Name: "Great Maul", Type: "hamm", NormalCode: "gma", UberCode: "9gm", UltraCode: "7gm"},
	25:  {Code: "ssd", Name: "Short Sword", Type: "swor", NormalCode: "ssd", UberCode: "9ss", UltraCode: "7ss"},
	26:  {Code: "scm", Name: "Scimitar", Type: "swor", NormalCode: "scm", UberCode: "9sm", UltraCode: "7sm"},
	27:  {Code: "sbr", Name: "Saber", Type: "swor", NormalCode: "sbr", UberCode: "9sb", UltraCode: "7sb", Width: 1, Height: 3},
	28:  {Code: "flc", Name: "Falchion", Type: "swor", NormalCode: "flc", UberCode: "9fc", UltraCode: "7fc"},
	29:  {Code: "crs", Name: "Crystal Sword", Type: "swor", NormalCode: "crs", UberCode: "9cr", UltraCode: "7cr"},
	30:  {Code: "bsd", Name: "Broad Sword", Type: "swor", NormalCode: "bsd", UberCode: "9bs", UltraCode: "7bs"},
	31:  {Code: "lsd", Name: "Long Sword", Type: "swor", NormalCode: "lsd", UberCode: "9ls", UltraCode: "7ls"},
	32:  {Code: "wsd", Name: "War Sword", Type: "swor", NormalCode: "wsd", UberCode: "9wd", UltraCode: "7wd"},
	33:  {Code: "2hs", Name: "Two-Handed Sword", Type: "swor", NormalCode: "2hs", UberCode: "92h", UltraCode: "72h"},
	34:  {Code: "clm", Name: "Claymore", Type: "swor", NormalCode: "clm", UberCode: "9cm", UltraCode: "7cm"},
	35:  {Code: "gis", Name: "Giant Sword", Type: "swor", NormalCode: "gis", UberCode: "9gs", UltraCode: "7gs"},
	36:  {Code: "bsw", Name: "Bastard Sword", Type: "swor", NormalCode: "bsw", UberCode: "9b9", UltraCode: "7b7"},
	37:  {Code: "flb", Name: "Flamberge", Type: "swor", NormalCode: "flb", UberCode: "9fb", UltraCode: "7fb"},
	38:  {Code: "gsd", Name: "Great Sword", Type: "swor", NormalCode: "gsd", UberCode: "9gd", UltraCode: "7gd"},
	39:  {Code: "dgr", Name: "Dagger", Type: "knif", NormalCode: "dgr", UberCode: "9dg", UltraCode: "7dg"},
	40:  {Code: "dir", Name: "Dirk", Type: "knif", NormalCode: "dir", UberCode: "9di", UltraCode: "7di"},
	41:  {Code: "kri", Name: "Kriss", Type: "knif", NormalCode: "kri", UberCode: "9kr", UltraCode: "7kr"},
	42:  {Code: "bld", Name: "Blade", Type: "knif", NormalCode: "bld", UberCode: "9bl", UltraCode: "7bl"},
	43:  {Code: "tkf", Name: "Throwing Knife", Type: "tkni", NormalCode: "tkf", UberCode: "9tk", UltraCode: "7tk"},
	44:  {Code: "tax", Name: "Throwing Axe", Type: "taxe", NormalCode: "tax", UberCode: "9ta", UltraCode: "7ta"},
	45:  {Code: "bkf", Name: "Balanced Knife", Type: "tkni", NormalCode: "bkf", UberCode: "9bk", UltraCode: "7bk"},
	46:  {Code: "bal", Name: "Balanced Axe", Type: "taxe", NormalCode: "bal", UberCode: "9b8", UltraCode: "7b8"},
	47:  {Code: "jav", Name: "Javelin", Type: "jave", NormalCode: "jav", UberCode: "9ja", UltraCode: "7ja"},
	48:  {Code: "pil", Name: "Pilum", Type: "jave", NormalCode: "pil", UberCode: "9pi", UltraCode: "7pi"},
	49:  {Code: "ssp", Name: "Short Spear", Type: "jave", NormalCode: "ssp", UberCode: "9s9", UltraCode: "7s7"},
	50:  {Code: "glv", Name: "Glaive", Type: "jave", NormalCode: "glv", UberCode: "9gl", UltraCode: "7gl"},
	51:  {Code: "tsp", Name: "Throwing Spear", Type: "jave", NormalCode: "tsp", UberCode: "9ts", UltraCode: "7ts"},
	52:  {Code: "spr", Name: "Spear", Type: "spea", NormalCode: "spr", UberCode: "9sr", UltraCode: "7sr"},
	53:  {Code: "tri", Name: "Trident", Type: "spea", NormalCode: "tri", UberCode: "9tr", UltraCode: "7tr"},
	54:  {Code: "brn", Name: "Brandistock", Type: "spea", NormalCode: "brn", UberCode: "9br", UltraCode: "7br"},
	55:  {Code: "spt", Name: "Spetum", Type: "spea", NormalCode: "spt", UberCode: "9st", UltraCode: "7st"},
	56:  {Code: "pik", Name: "Pike", Type: "spea", NormalCode: "pik", UberCode: "9p9", UltraCode: "7p7"},
	57:  {Code: "bar", Name: "Bardiche", Type: "pole", NormalCode: "bar", UberCode: "9b7", UltraCode: "7o7"},
	58:  {Code: "vou", Name: "Voulge", Type: "pole", NormalCode: "vou", UberCode: "9vo", UltraCode: "7vo"},
	59:  {Code: "scy", Name: "Scythe", Type: "pole", NormalCode: "scy", UberCode: "9s8", UltraCode: "7s8"},
	60:  {Code: "pax", Name: "Poleaxe", Type: "pole", NormalCode: "pax", UberCode: "9pa", UltraCode: "7pa"},
	61:  {Code: "hal", Name: "Halberd", Type: "pole", NormalCode: "hal", UberCode: "9h9", UltraCode: "7h7"},
	62:  {Code: "wsc", Name: "War Scythe", Type: "pole", NormalCode: "wsc", UberCode: "9wc", UltraCode: "7wc"},
	63:  {Code: "sst", Name: "Short Staff", Type: "staf", NormalCode: "sst", UberCode: "8ss", UltraCode: "6ss"},
	64:  {Code: "lst", Name: "Long Staff", Type: "staf", NormalCode: "lst", UberCode: "8ls", UltraCode: "6ls"},
	65:  {Code: "cst", Name: "Gnarled Staff", Type: "staf", NormalCode: "cst", UberCode: "8cs", UltraCode: "6cs"},
	66:  {Code: "bst", Name: "Battle Staff", Type: "staf", NormalCode: "bst", UberCode: "8bs", UltraCode: "6bs"},
	67:  {Code: "wst", Name: "War Staff", Type: "staf", NormalCode: "wst", UberCode: "8ws", UltraCode: "6ws"},
	68:  {Code: "sbw", Name: "Short Bow", Type: "bow", NormalCode: "sbw", UberCode: "8sb", UltraCode: "6sb"},
	69:  {Code: "hbw", Name: "Hunter's Bow", Type: "bow", NormalCode: "hbw", UberCode: "8hb", UltraCode: "6hb"},
	70:  {Code: "lbw", Name: "Long Bow", Type: "bow", NormalCode: "lbw", UberCode: "8lb", UltraCode: "6lb"},
	71:  {Code: "cbw", Name: "Composite Bow", Type: "bow", NormalCode: "cbw", UberCode: "8cb", UltraCode: "6cb"},
	72:  {Code: "sbb", Name: "Short Battle Bow", Type: "bow", NormalCode: "sbb", UberCode: "8s8", UltraCode: "6s7"},
	73:  {Code: "lbb", Name: "Long Battle Bow", Type: "bow", NormalCode: "lbb", UberCode: "8l8", UltraCode: "6l7"},
	74:  {Code: "swb", Name: "Short War Bow", Type: "bow", NormalCode: "swb", UberCode: "8sw", UltraCode: "6sw"},
	75:  {Code: "lwb", Name: "Long War Bow", Type: "bow", NormalCode: "lwb", UberCode: "8lw", UltraCode: "6lw"},
	76:  {Code: "lxb", Name: "Light Crossbow", Type: "xbow", NormalCode: "lxb", UberCode: "8lx", UltraCode: "6lx"},
	77:  {Code: "mxb", Name: "Crossbow", Type: "xbow", NormalCode: "mxb", UberCode: "8mx", UltraCode: "6mx"},
	78:  {Code: "hxb", Name: "Heavy Crossbow", Type: "xbow", NormalCode: "hxb", UberCode: "8hx", UltraCode: "6hx"},
	79:  {Code: "rxb", Name: "Repeating Crossbow", Type: "xbow", NormalCode: "rxb", UberCode: "8rx", UltraCode: "6rx"},
	80:  {Code: "gps", Name: "Rancid Gas Potion", Type: "tpot", NormalCode: "gps", UberCode: "", UltraCode: ""},
	81:  {Code: "ops", Name: "Oil Potion", Type: "tpot", NormalCode: "ops", UberCode: "", UltraCode: ""},
	82:  {Code: "gpm", Name: "Choking Gas Potion", Type: "tpot", NormalCode: "gpm", UberCode: "", UltraCode: ""},
	83:  {Code: "opm", Name: "Exploding Potion", Type: "tpot", NormalCode: "opm", UberCode: "", UltraCode: ""},
	84:  {Code: "gpl", Name: "Strangling Gas Potion", Type: "tpot", NormalCode: "gpl", UberCode: "", UltraCode: ""},
	85:  {Code: "opl", Name: "Fulminating Potion", Type: "tpot", NormalCode: "opl", UberCode: "", UltraCode: ""},
	86:  {Code: "d33", Name: "Decoy Gidbinn", Type: "knif", NormalCode: "d33", UberCode: "", UltraCode: ""},
	87:  {Code: "g33", Name: "The Gidbinn", Type: "knif", NormalCode: "g33", UberCode: "", UltraCode: ""},
	88:  {Code: "leg", Name: "Wirt's Leg", Type: "club", NormalCode: "leg", UberCode: "", UltraCode: ""},
	89:  {Code: "hdm", Name: "Horadric Malus", Type: "hamm", NormalCode: "hdm", UberCode: "", UltraCode: ""},
	90:  {Code: "hfh", Name: "Hellforge Hammer", Type: "hamm", NormalCode: "hfh", UberCode: "", UltraCode: ""},
	91:  {Code: "hst", Name: "Horadric Staff", Type: "staf", NormalCode: "hst", UberCode: "", UltraCode: ""},
	92:  {Code: "msf", Name: "Staff of Kings", Type: "staf", NormalCode: "msf", UberCode: "", UltraCode: ""},
	93:  {Code: "9ha", Name: "Hatchet", Type: "axe", NormalCode: "hax", UberCode: "9ha", UltraCode: "7ha"},
	94:  {Code: "9ax", Name: "Cleaver", Type: "axe", NormalCode: "axe", UberCode: "9ax", UltraCode: "7ax"},
	95:  {Code: "92a", Name: "Twin Axe", Type: "axe", NormalCode: "2ax", UberCode: "92a", UltraCode: "72a"},
	96:  {Code: "9mp", Name: "Crowbill", Type: "axe", NormalCode: "mpi", UberCode: "9mp", UltraCode: "7mp"},
	97:  {Code: "9wa", Name: "Naga", Type: "axe", NormalCode: "wax", UberCode: "9wa", UltraCode: "7wa"},
	98:  {Code: "9la", Name: "Military Axe", Type: "axe", NormalCode: "lax", UberCode: "9la", UltraCode: "7la"},
	99:  {Code: "9ba", Name: "Bearded Axe", Type: "axe", NormalCode: "bax", UberCode: "9ba", UltraCode: "7ba"},
	100: {Code: "9bt", Name: "Tabar", Type: "axe", NormalCode: "btx", UberCode: "9bt", UltraCode: "7bt"},
	101: {Code: "9ga", Name: "Gothic Axe", Type: "axe", NormalCode: "gax", UberCode: "9ga", UltraCode: "7ga"},
	102: {Code: "9gi", Name: "Ancient Axe", Type: "axe", NormalCode: "gix", UberCode: "9gi", UltraCode: "7gi"},
	103: {Code: "9wn", Name: "Burnt Wand", Type: "wand", NormalCode: "wnd", UberCode: "9wn", UltraCode: "7wn"},
	104: {Code: "9yw", Name: "Petrified Wand", Type: "wand", NormalCode: "ywn", UberCode: "9yw", UltraCode: "7yw"},
	105: {Code: "9bw", Name: "Tomb Wand", Type: "wand", NormalCode: "bwn", UberCode: "9bw", UltraCode: "7bw"},
	106: {Code: "9gw", Name: "Grave Wand", Type: "wand", NormalCode: "gwn", UberCode: "9gw", UltraCode: "7gw"},
	107: {Code: "9cl", Name: "Cudgel", Type: "club", NormalCode: "clb", UberCode: "9cl", UltraCode: "7cl"},
	108: {Code: "9sc", Name: "Rune Scepter", Type: "scep", NormalCode: "scp", UberCode: "9sc", UltraCode: "7sc"},
	109: {Code: "9qs", Name: "Holy Water Sprinkler", Type: "scep", NormalCode: "gsc", UberCode: "9qs", UltraCode: "7qs"},
	110: {Code: "9ws", Name: "Divine Scepter", Type: "scep", NormalCode: "wsp", UberCode: "9ws", UltraCode: "7ws"},
	111: {Code: "9sp", Name: "Barbed Club", Type: "club", NormalCode: "spc", UberCode: "9sp", UltraCode: "7sp"},
	112: {Code: "9ma", Name: "Flanged Mace", Type: "mace", NormalCode: "mac", UberCode: "9ma", UltraCode: "7ma"},
	113: {Code: "9mt", Name: "Jagged Star", Type: "mace", NormalCode: "mst", UberCode: "9mt", UltraCode: "7mt"},
	114: {Code: "9fl", Name: "Knout", Type: "mace", NormalCode: "fla", UberCode: "9fl", UltraCode: "7fl"},
	115: {Code: "9wh", Name: "Battle Hammer", Type: "hamm", NormalCode: "whm", UberCode: "9wh", UltraCode: "7wh"},
	116: {Code: "9m9", Name: "War Club", Type: "hamm", NormalCode: "mau", UberCode: "9m9", UltraCode: "7m7"},
	117: {Code: "9gm", Name: "Martel de Fer", Type: "hamm", NormalCode: "gma", UberCode: "9gm", UltraCode: "7gm"},
	118: {Code: "9ss", Name: "Gladius", Type: "swor", NormalCode: "ssd", UberCode: "9ss", UltraCode: "7ss"},
	119: {Code: "9sm", Name: "Cutlass", Type: "swor", NormalCode: "scm", UberCode: "9sm", UltraCode: "7sm"},
	120: {Code: "9sb", Name: "Shamshir", Type: "swor", NormalCode: "sbr", UberCode: "9sb", UltraCode: "7sb"},
	121: {Code: "9fc", Name: "Tulwar", Type: "swor", NormalCode: "flc", UberCode: "9fc", UltraCode: "7fc"},
	122: {Code: "9cr", Name: "Dimensional Blade", Type: "swor", NormalCode: "crs", UberCode: "9cr", UltraCode: "7cr"},
	123: {Code: "9bs", Name: "Battle Sword", Type: "swor", NormalCode: "bsd", UberCode: "9bs", UltraCode: "7bs"},
	124: {Code: "9ls", Name: "Rune Sword", Type: "swor", NormalCode: "lsd", UberCode: "9ls", UltraCode: "7ls"},
	125: {Code: "9wd", Name: "Ancient Sword", Type: "swor", NormalCode: "wsd", UberCode: "9wd", UltraCode: "7wd"},
	126: {Code: "92h", Name: "Espandon", Type: "swor", NormalCode: "2hs", UberCode: "92h", UltraCode: "72h"},
	127: {Code: "9cm", Name: "Dacian Falx", Type: "swor", NormalCode: "clm", UberCode: "9cm", UltraCode: "7cm"},
	128: {Code: "9gs", Name: "Tusk Sword", Type: "swor", NormalCode: "gis", UberCode: "9gs", UltraCode: "7gs"},
	129: {Code: "9b9", Name: "Gothic Sword", Type: "swor", NormalCode: "bsw", UberCode: "9b9", UltraCode: "7b7"},
	130: {Code: "9fb", Name: "Zweihander", Type: "swor", NormalCode: "flb", UberCode: "9fb", UltraCode: "7fb"},
	131: {Code: "9gd", Name: "Executioner Sword", Type: "swor", NormalCode: "gsd", UberCode: "9gd", UltraCode: "7gd"},
	132: {Code: "9dg", Name: "Poignard", Type: "knif", NormalCode: "dgr", UberCode: "9dg", UltraCode: "7dg"},
	133: {Code: "9di", Name: "Rondel", Type: "knif", NormalCode: "dir", UberCode: "9di", UltraCode: "7di"},
	134: {Code: "9kr", Name: "Cinquedeas", Type: "knif", NormalCode: "kri", UberCode: "9kr", UltraCode: "7kr"},
	135: {Code: "9bl", Name: "Stilleto", Type: "knif", NormalCode: "bld", UberCode: "9bl", UltraCode: "7bl"},
	136: {Code: "9tk", Name: "Battle Dart", Type: "tkni", NormalCode: "tkf", UberCode: "9tk", UltraCode: "7tk"},
	137: {Code: "9ta", Name: "Francisca", Type: "taxe", NormalCode: "tax", UberCode: "9ta", UltraCode: "7ta"},
	138: {Code: "9bk", Name: "War Dart", Type: "tkni", NormalCode: "bkf", UberCode: "9bk", UltraCode: "7bk"},
	139: {Code: "9b8", Name: "Hurlbat", Type: "taxe", NormalCode: "bal", UberCode: "9b8", UltraCode: "7b8"},
	140: {Code: "9ja", Name: "War Javelin", Type: "jave", NormalCode: "jav", UberCode: "9ja", UltraCode: "7ja"},
	141: {Code: "9pi", Name: "Great Pilum", Type: "jave", NormalCode: "pil", UberCode: "9pi", UltraCode: "7pi"},
	142: {Code: "9s9", Name: "Simbilan", Type: "jave", NormalCode: "ssp", UberCode: "9s9", UltraCode: "7s7"},
	143: {Code: "9gl", Name: "Spiculum", Type: "jave", NormalCode: "glv", UberCode: "9gl", UltraCode: "7gl"},
	144: {Code: "9ts", Name: "Harpoon", Type: "jave", NormalCode: "tsp", UberCode: "9ts", UltraCode: "7ts"},
	145: {Code: "9sr", Name: "War Spear", Type: "spea", NormalCode: "spr", UberCode: "9sr", UltraCode: "7sr"},
	146: {Code: "9tr", Name: "Fuscina", Type: "spea", NormalCode: "tri", UberCode: "9tr", UltraCode: "7tr"},
	147: {Code: "9br", Name: "War Fork", Type: "spea", NormalCode: "brn", UberCode: "9br", UltraCode: "7br"},
	148: {Code: "9st", Name: "Yari", Type: "spea", NormalCode: "spt", UberCode: "9st", UltraCode: "7st"},
	149: {Code: "9p9", Name: "Lance", Type: "spea", NormalCode: "pik", UberCode: "9p9", UltraCode: "7p7"},
	150: {Code: "9b7", Name: "Lochaber Axe", Type: "pole", NormalCode: "bar", UberCode: "9b7", UltraCode: "7o7"},
	151: {Code: "9vo", Name: "Bill", Type: "pole", NormalCode: "vou", UberCode: "9vo", UltraCode: "7vo"},
	152: {Code: "9s8", Name: "Battle Scythe", Type: "pole", NormalCode: "scy", UberCode: "9s8", UltraCode: "7s8"},
	153: {Code: "9pa", Name: "Partizan", Type: "pole", NormalCode: "pax", UberCode: "9pa", UltraCode: "7pa"},
	154: {Code: "9h9", Name: "Bec-de-Corbin", Type: "pole", NormalCode: "hal", UberCode: "9h9", UltraCode: "7h7"},
	155: {Code: "9wc", Name: "Grim Scythe", Type: "pole", NormalCode: "wsc", UberCode: "9wc", UltraCode: "7wc"},
	156: {Code: "8ss", Name: "Jo Staff", Type: "staf", NormalCode: "sst", UberCode: "8ss", UltraCode: "6ss"},
	157: {Code: "8ls", Name: "Quarterstaff", Type: "staf", NormalCode: "lst", UberCode: "8ls", UltraCode: "6ls"},
	158: {Code: "8cs", Name: "Cedar Staff", Type: "staf", NormalCode: "cst", UberCode: "8cs", UltraCode: "6cs"},
	159: {Code: "8bs", Name: "Gothic Staff", Type: "staf", NormalCode: "bst", UberCode: "8bs", UltraCode: "6bs"},
	160: {Code: "8ws", Name: "Rune Staff", Type: "staf", NormalCode: "wst", UberCode: "8ws", UltraCode: "6ws"},
	161: {Code: "8sb", Name: "Edge Bow", Type: "bow", NormalCode: "sbw", UberCode: "8sb", UltraCode: "6sb"},
	162: {Code: "8hb", Name: "Razor Bow", Type: "bow", NormalCode: "hbw", UberCode: "8hb", UltraCode: "6hb"},
	163: {Code: "8lb", Name: "Cedar Bow", Type: "bow", NormalCode: "lbw", UberCode: "8lb", UltraCode: "6lb"},
	164: {Code: "8cb", Name: "Double Bow", Type: "bow", NormalCode: "cbw", UberCode: "8cb", UltraCode: "6cb"},
	165: {Code: "8s8", Name: "Short Siege Bow", Type: "bow", NormalCode: "sbb", UberCode: "8s8", UltraCode: "6s7"},
	166: {Code: "8l8", Name: "Long Siege Bow", Type: "bow", NormalCode: "lbb", UberCode: "8l8", UltraCode: "6l7"},
	167: {Code: "8sw", Name: "Rune Bow", Type: "bow", NormalCode: "swb", UberCode: "8sw", UltraCode: "6sw"},
	168: {Code: "8lw", Name: "Gothic Bow", Type: "bow", NormalCode: "lwb", UberCode: "8lw", UltraCode: "6lw"},
	169: {Code: "8lx", Name: "Arbalest", Type: "xbow", NormalCode: "lxb", UberCode: "8lx", UltraCode: "6lx"},
	170: {Code: "8mx", Name: "Siege Crossbow", Type: "xbow", NormalCode: "mxb", UberCode: "8mx", UltraCode: "6mx"},
	171: {Code: "8hx", Name: "Ballista", Type: "xbow", NormalCode: "hxb", UberCode: "8hx", UltraCode: "6hx"},
	172: {Code: "8rx", Name: "Chu-Ko-Nu", Type: "xbow", NormalCode: "rxb", UberCode: "8rx", UltraCode: "6rx"},
	173: {Code: "qf1", Name: "Khalim's Flail", Type: "mace", NormalCode: "fla", UberCode: "", UltraCode: ""},
	174: {Code: "qf2", Name: "Khalim's Will", Type: "mace", NormalCode: "fla", UberCode: "", UltraCode: ""},
	175: {Code: "ktr", Name: "Katar", Type: "h2h", NormalCode: "ktr", UberCode: "9ar", UltraCode: "7ar"},
	176: {Code: "wrb", Name: "Wrist Blade", Type: "h2h", NormalCode: "wrb", UberCode: "9wb", UltraCode: "7wb"},
	177: {Code: "axf", Name: "Hatchet Hands", Type: "h2h", NormalCode: "axf", UberCode: "9xf", UltraCode: "7xf"},
	178: {Code: "ces", Name: "Cestus", Type: "h2h", NormalCode: "ces", UberCode: "9cs", UltraCode: "7cs"},
	179: {Code: "clw", Name: "Claws", Type: "h2h", NormalCode: "clw", UberCode: "9lw", UltraCode: "7lw"},
	180: {Code: "btl", Name: "Blade Talons", Type: "h2h", NormalCode: "btl", UberCode: "9tw", UltraCode: "7tw"},
	181: {Code: "skr", Name: "Scissors Katar", Type: "h2h", NormalCode: "skr", UberCode: "9qr", UltraCode: "7qr"},
	182: {Code: "9ar", Name: "Quhab", Type: "h2h", NormalCode: "ktr", UberCode: "9ar", UltraCode: "7ar"},
	183: {Code: "9wb", Name: "Wrist Spike", Type: "h2h", NormalCode: "wrb", UberCode: "9wb", UltraCode: "7wb"},
	184: {Code: "9xf", Name: "Fascia", Type: "h2h", NormalCode: "axf", UberCode: "9xf", UltraCode: "7xf"},
	185: {Code: "9cs", Name: "Hand Scythe", Type: "h2h2", NormalCode: "ces", UberCode: "9cs", UltraCode: "7cs"},
	186: {Code: "9lw", Name: "Greater Claws", Type: "h2h2", NormalCode: "clw", UberCode: "9lw", UltraCode: "7lw"},
	187: {Code: "9tw", Name: "Greater Talons", Type: "h2h2", NormalCode: "btl", UberCode: "9tw", UltraCode: "7tw"},
	188: {Code: "9qr", Name: "Scissors Quhab", Type: "h2h2", NormalCode: "skr", UberCode: "9qr", UltraCode: "7qr"},
	189: {Code: "7ar", Name: "Suwayyah", Type: "h2h2", NormalCode: "ktr", UberCode: "9ar", UltraCode: "7ar"},
	190: {Code: "7wb", Name: "Wrist Sword", Type: "h2h2", NormalCode: "wrb", UberCode: "9wb", UltraCode: "7wb"},
	191: {Code: "7xf", Name: "War Fist", Type: "h2h2", NormalCode: "axf", UberCode: "9xf", UltraCode: "7xf"},
	192: {Code: "7cs", Name: "Battle Cestus", Type: "h2h2", NormalCode: "ces", UberCode: "9cs", UltraCode: "7cs"},
	193: {Code: "7lw", Name: "Feral Claws", Type: "h2h2", NormalCode: "clw", UberCode: "9lw", UltraCode: "7lw"},
	194: {Code: "7tw", Name: "Runic Talons", Type: "h2h2", NormalCode: "btl", UberCode: "9tw", UltraCode: "7tw"},
	195: {Code: "7qr", Name: "Scissors Suwayyah", Type: "h2h2", NormalCode: "skr", UberCode: "9qr", UltraCode: "7qr"},
	196: {Code: "7ha", Name: "Tomahawk", Type: "axe", NormalCode: "hax", UberCode: "9ha", UltraCode: "7ha"},
	197: {Code: "7ax", Name: "Small Crescent", Type: "axe", NormalCode: "axe", UberCode: "9ax", UltraCode: "7ax"},
	198: {Code: "72a", Name: "Ettin Axe", Type: "axe", NormalCode: "2ax", UberCode: "92a", UltraCode: "72a"},
	199: {Code: "7mp", Name: "War Spike", Type: "axe", NormalCode: "mpi", UberCode: "9mp", UltraCode: "7mp"},
	200: {Code: "7wa", Name: "Berserker Axe", Type: "axe", NormalCode: "wax", UberCode: "9wa", UltraCode: "7wa"},
	201: {Code: "7la", Name: "Feral Axe", Type: "axe", NormalCode: "lax", UberCode: "9la", UltraCode: "7la"},
	202: {Code: "7ba", Name: "Silver-edged Axe", Type: "axe", NormalCode: "bax", UberCode: "9ba", UltraCode: "7ba"},
	203: {Code: "7bt", Name: "Decapitator", Type: "axe", NormalCode: "btx", UberCode: "9bt", UltraCode: "7bt"},
	204: {Code: "7ga", Name: "Champion Axe", Type: "axe", NormalCode: "gax", UberCode: "9ga", UltraCode: "7ga"},
	205: {Code: "7gi", Name: "Glorious Axe", Type: "axe", NormalCode: "gix", UberCode: "9gi", UltraCode: "7gi"},
	206: {Code: "7wn", Name: "Polished Wand", Type: "wand", NormalCode: "wnd", UberCode: "9wn", UltraCode: "7wn"},
	207: {Code: "7yw", Name: "Ghost Wand", Type: "wand", NormalCode: "ywn", UberCode: "9yw", UltraCode: "7yw"},
	208: {Code: "7bw", Name: "Lich Wand", Type: "wand", NormalCode: "bwn", UberCode: "9bw", UltraCode: "7bw"},
	209: {Code: "7gw", Name: "Unearthed Wand", Type: "wand", NormalCode: "gwn", UberCode: "9gw", UltraCode: "7gw"},
	210: {Code: "7cl", Name: "Truncheon", Type: "club", NormalCode: "clb", UberCode: "9cl", UltraCode: "7cl"},
	211: {Code: "7sc", Name: "Mighty Scepter", Type: "scep", NormalCode: "scp", UberCode: "9sc", UltraCode: "7sc"},
	212: {Code: "7qs", Name: "Seraph Rod", Type: "scep", NormalCode: "gsc", UberCode: "9qs", UltraCode: "7qs"},
	213: {Code: "7ws", Name: "Caduceus", Type: "scep", NormalCode: "wsp", UberCode: "9ws", UltraCode: "7ws"},
	214: {Code: "7sp", Name: "Tyrant Club", Type: "club", NormalCode: "spc", UberCode: "9sp", UltraCode: "7sp"},
	215: {Code: "7ma", Name: "Reinforced Mace", Type: "mace", NormalCode: "mac", UberCode: "9ma", UltraCode: "7ma"},
	216: {Code: "7mt", Name: "Devil Star", Type: "mace", NormalCode: "mst", UberCode: "9mt", UltraCode: "7mt"},
	217: {Code: "7fl", Name: "Scourge", Type: "mace", NormalCode: "fla", UberCode: "9fl", UltraCode: "7fl"},
	218: {Code: "7wh", Name: "Legendary Mallet", Type: "hamm", NormalCode: "whm", UberCode: "9wh", UltraCode: "7wh"},
	219: {Code: "7m7", Name: "Ogre Maul", Type: "hamm", NormalCode: "mau", UberCode: "9m9", UltraCode: "7m7"},
	220: {Code: "7gm", Name: "Thunder Maul", Type: "hamm", NormalCode: "gma", UberCode: "9gm", UltraCode: "7gm"},
	221: {Code: "7ss", Name: "Falcata", Type: "swor", NormalCode: "ssd", UberCode: "9ss", UltraCode: "7ss"},
	222: {Code: "7sm", Name: "Ataghan", Type: "swor", NormalCode: "scm", UberCode: "9sm", UltraCode: "7sm"},
	223: {Code: "7sb", Name: "Elegant Blade", Type: "swor", NormalCode: "sbr", UberCode: "9sb", UltraCode: "7sb"},
	224: {Code: "7fc", Name: "Hydra Edge", Type: "swor", NormalCode: "flc", UberCode: "9fc", UltraCode: "7fc"},
	225: {Code: "7cr", Name: "Phase Blade", Type: "swor", NormalCode: "crs", UberCode: "9cr", UltraCode: "7cr"},
	226: {Code: "7bs", Name: "Conquest Sword", Type: "swor", NormalCode: "bsd", UberCode: "9bs", UltraCode: "7bs"},
	227: {Code: "7ls", Name: "Cryptic Sword", Type: "swor", NormalCode: "lsd", UberCode: "9ls", UltraCode: "7ls"},
	228: {Code: "7wd", Name: "Mythical Sword", Type: "swor", NormalCode: "wsd", UberCode: "9wd", UltraCode: "7wd"},
	229: {Code: "72h", Name: "Legend Sword", Type: "swor", NormalCode: "2hs", UberCode: "92h", UltraCode: "72h"},
	230: {Code: "7cm", Name: "Highland Blade", Type: "swor", NormalCode: "clm", UberCode: "9cm", UltraCode: "7cm"},
	231: {Code: "7gs", Name: "Balrog Blade", Type: "swor", NormalCode: "gis", UberCode: "9gs", UltraCode: "7gs"},
	232: {Code: "7b7", Name: "Champion Sword", Type: "swor", NormalCode: "bsw", UberCode: "9b9", UltraCode: "7b7"},
	233: {Code: "7fb", Name: "Colossal Sword", Type: "swor", NormalCode: "flb", UberCode: "9fb", UltraCode: "7fb"},
	234: {Code: "7gd", Name: "Colossus Blade", Type: "swor", NormalCode: "gsd", UberCode: "9gd", UltraCode: "7gd"},
	235: {Code: "7dg", Name: "Bone Knife", Type: "knif", NormalCode: "dgr", UberCode: "9dg", UltraCode: "7dg"},
	236: {Code: "7di", Name: "Mithral Point", Type: "knif", NormalCode: "dir", UberCode: "9di", UltraCode: "7di"},
	237: {Code: "7kr", Name: "Fanged Knife", Type: "knif", NormalCode: "kri", UberCode: "9kr", UltraCode: "7kr"},
	238: {Code: "7bl", Name: "Legend Spike", Type: "knif", NormalCode: "bld", UberCode: "9bl", UltraCode: "7bl"},
	239: {Code: "7tk", Name: "Flying Knife", Type: "tkni", NormalCode: "tkf", UberCode: "9tk", UltraCode: "7tk"},
	240: {Code: "7ta", Name: "Flying Axe", Type: "taxe", NormalCode: "tax", UberCode: "9ta", UltraCode: "7ta"},
	241: {Code: "7bk", Name: "Winged Knife", Type: "tkni", NormalCode: "bkf", UberCode: "9bk", UltraCode: "7bk"},
	242: {Code: "7b8", Name: "Winged Axe", Type: "taxe", NormalCode: "bal", UberCode: "9b8", UltraCode: "7b8"},
	243: {Code: "7ja", Name: "Hyperion Javelin", Type: "jave", NormalCode: "jav", UberCode: "9ja", UltraCode: "7ja"},
	244: {Code: "7pi", Name: "Stygian Pilum", Type: "jave", NormalCode: "pil", UberCode: "9pi", UltraCode: "7pi"},
	245: {Code: "7s7", Name: "Balrog Spear", Type: "jave", NormalCode: "ssp", UberCode: "9s9", UltraCode: "7s7"},
	246: {Code: "7gl", Name: "Ghost Glaive", Type: "jave", NormalCode: "glv", UberCode: "9gl", UltraCode: "7gl"},
	247: {Code: "7ts", Name: "Winged Harpoon", Type: "jave", NormalCode: "tsp", UberCode: "9ts", UltraCode: "7ts"},
	248: {Code: "7sr", Name: "Hyperion Spear", Type: "spea", NormalCode: "spr", UberCode: "9sr", UltraCode: "7sr"},
	249: {Code: "7tr", Name: "Stygian Pike", Type: "spea", NormalCode: "tri", UberCode: "9tr", UltraCode: "7tr"},
	250: {Code: "7br", Name: "Mancatcher", Type: "spea", NormalCode: "brn", UberCode: "9br", UltraCode: "7br"},
	251: {Code: "7st", Name: "Ghost Spear", Type: "spea", NormalCode: "spt", UberCode: "9st", UltraCode: "7st"},
	252: {Code: "7p7", Name: "War Pike", Type: "spea", NormalCode: "pik", UberCode: "9p9", UltraCode: "7p7"},
	253: {Code: "7o7", Name: "Ogre Axe", Type: "pole", NormalCode: "bar", UberCode: "9b7", UltraCode: "7o7"},
	254: {Code: "7vo", Name: "Colossus Voulge", Type: "pole", NormalCode: "vou", UberCode: "9vo", UltraCode: "7vo"},
	255: {Code: "7s8", Name: "Thresher", Type: "pole", NormalCode: "scy", UberCode: "9s8", UltraCode: "7s8"},
	256: {Code: "7pa", Name: "Cryptic Axe", Type: "pole", NormalCode: "pax", UberCode: "9pa", UltraCode: "7pa"},
	257: {Code: "7h7", Name: "Great Poleaxe", Type: "pole", NormalCode: "hal", UberCode: "9h9", UltraCode: "7h7"},
	258: {Code: "7wc", Name: "Giant Thresher", Type: "pole", NormalCode: "wsc", UberCode: "9wc", UltraCode: "7wc"},
	259: {Code: "6ss", Name: "Walking Stick", Type: "staf", NormalCode: "sst", UberCode: "8ss", UltraCode: "6ss"},
	260: {Code: "6ls", Name: "Stalagmite", Type: "staf", NormalCode: "lst", UberCode: "8ls", UltraCode: "6ls"},
	261: {Code: "6cs", Name: "Elder Staff", Type: "staf", NormalCode: "cst", UberCode: "8cs", UltraCode: "6cs"},
	262: {Code: "6bs", Name: "Shillelagh", Type: "staf", NormalCode: "bst", UberCode: "8bs", UltraCode: "6bs"},
	263: {Code: "6ws", Name: "Archon Staff", Type: "staf", NormalCode: "wst", UberCode: "8ws", UltraCode: "6ws"},
	264: {Code: "6sb", Name: "Spider Bow", Type: "bow", NormalCode: "sbw", UberCode: "8sb", UltraCode: "6sb"},
	265: {Code: "6hb", Name: "Blade Bow", Type: "bow", NormalCode: "hbw", UberCode: "8hb", UltraCode: "6hb"},
	266: {Code: "6lb", Name: "Shadow Bow", Type: "bow", NormalCode: "lbw", UberCode: "8lb", UltraCode: "6lb"},
	267: {Code: "6cb", Name: "Great Bow", Type: "bow", NormalCode: "cbw", UberCode: "8cb", UltraCode: "6cb"},
	268: {Code: "6s7", Name: "Diamond Bow", Type: "bow", NormalCode: "sbb", UberCode: "8s8", UltraCode: "6s7"},
	269: {Code: "6l7", Name: "Crusader Bow", Type: "bow", NormalCode: "lbb", UberCode: "8l8", UltraCode: "6l7"},
	270: {Code: "6sw", Name: "Ward Bow", Type: "bow", NormalCode: "swb", UberCode: "8sw", UltraCode: "6sw"},
	271: {Code: "6lw", Name: "Hydra Bow", Type: "bow", NormalCode: "lwb", UberCode: "8lw", UltraCode: "6lw"},
	272: {Code: "6lx", Name: "Pellet Bow", Type: "xbow", NormalCode: "lxb", UberCode: "8lx", UltraCode: "6lx"},
	273: {Code: "6mx", Name: "Gorgon Crossbow", Type: "xbow", NormalCode: "mxb", UberCode: "8mx", UltraCode: "6mx"},
	274: {Code: "6hx", Name: "Colossus Crossbow", Type: "xbow", NormalCode: "hxb", UberCode: "8hx", UltraCode: "6hx"},
	275: {Code: "6rx", Name: "Demon Crossbow", Type: "xbow", NormalCode: "rxb", UberCode: "8rx", UltraCode: "6rx"},
	276: {Code: "ob1", Name: "Eagle Orb", Type: "orb", NormalCode: "ob1", UberCode: "ob6", UltraCode: "obb"},
	277: {Code: "ob2", Name: "Sacred Globe", Type: "orb", NormalCode: "ob2", UberCode: "ob7", UltraCode: "obc"},
	278: {Code: "ob3", Name: "Smoked Sphere", Type: "orb", NormalCode: "ob3", UberCode: "ob8", UltraCode: "obd"},
	279: {Code: "ob4", Name: "Clasped Orb", Type: "orb", NormalCode: "ob4", UberCode: "ob9", UltraCode: "obe"},
	280: {Code: "ob5", Name: "Jared's Stone", Type: "orb", NormalCode: "ob5", UberCode: "oba", UltraCode: "obf"},
	281: {Code: "am1", Name: "Stag Bow", Type: "abow", NormalCode: "am1", UberCode: "am6", UltraCode: "amb"},
	282: {Code: "am2", Name: "Reflex Bow", Type: "abow", NormalCode: "am2", UberCode: "am7", UltraCode: "amc"},
	283: {Code: "am3", Name: "Maiden Spear", Type: "aspe", NormalCode: "am3", UberCode: "am8", UltraCode: "amd"},
	284: {Code: "am4", Name: "Maiden Pike", Type: "aspe", NormalCode: "am4", UberCode: "am9", UltraCode: "ame"},
	285: {Code: "am5", Name: "Maiden Javelin", Type: "ajav", NormalCode: "am5", UberCode: "ama", UltraCode: "amf"},
	286: {Code: "ob6", Name: "Glowing Orb", Type: "orb", NormalCode: "ob1", UberCode: "ob6", UltraCode: "obb"},
	287: {Code: "ob7", Name: "Crystalline Globe", Type: "orb", NormalCode: "ob2", UberCode: "ob7", UltraCode: "obc"},
	288: {Code: "ob8", Name: "Cloudy Sphere", Type: "orb", NormalCode: "ob3", UberCode: "ob8", UltraCode: "obd"},
	289: {Code: "ob9", Name: "Sparkling Ball", Type: "orb", NormalCode: "ob4", UberCode: "ob9", UltraCode: "obe"},
	290: {Code: "oba", Name: "Swirling Crystal", Type: "orb", NormalCode: "ob5", UberCode: "oba", UltraCode: "obf"},
	291: {Code: "am6", Name: "Ashwood Bow", Type: "abow", NormalCode: "am1", UberCode: "am6", UltraCode: "amb"},
	292: {Code: "am7", Name: "Ceremonial Bow", Type: "abow", NormalCode: "am2", UberCode: "am7", UltraCode: "amc"},
	293: {Code: "am8", Name: "Ceremonial Spear", Type: "aspe", NormalCode: "am3", UberCode: "am8", UltraCode: "amd"},
	294: {Code: "am9", Name: "Ceremonial Pike", Type: "aspe", NormalCode: "am4", UberCode: "am9", UltraCode: "ame"},
	295: {Code: "ama", Name: "Ceremonial Javelin", Type: "ajav", NormalCode: "am5", UberCode: "ama", UltraCode: "amf"},
	296: {Code: "obb", Name: "Heavenly Stone", Type: "orb", NormalCode: "ob1", UberCode: "ob6", UltraCode: "obb"},
	297: {Code: "obc", Name: "Eldritch Orb", Type: "orb", NormalCode: "ob2", UberCode: "ob7", UltraCode: "obc"},
	298: {Code: "obd", Name: "Demon Heart", Type: "orb", NormalCode: "ob3", UberCode: "ob8", UltraCode: "obd"},
	299: {Code: "obe", Name: "Vortex Orb", Type: "orb", NormalCode: "ob4", UberCode: "ob9", UltraCode: "obe"},
	300: {Code: "obf", Name: "Dimensional Shard", Type: "orb", NormalCode: "ob5", UberCode: "oba", UltraCode: "obf"},
	301: {Code: "amb", Name: "Matriarchal Bow", Type: "abow", NormalCode: "am1", UberCode: "am6", UltraCode: "amb"},
	302: {Code: "amc", Name: "Grand Matron Bow", Type: "abow", NormalCode: "am2", UberCode: "am7", UltraCode: "amc"},
	303: {Code: "amd", Name: "Matriarchal Spear", Type: "aspe", NormalCode: "am3", UberCode: "am8", UltraCode: "amd"},
	304: {Code: "ame", Name: "Matriarchal Pike", Type: "aspe", NormalCode: "am4", UberCode: "am9", UltraCode: "ame"},
	305: {Code: "amf", Name: "Matriarchal Javelin", Type: "ajav", NormalCode: "am5", UberCode: "ama", UltraCode: "amf"},
	306: {Code: "cap", Name: "Cap", Type: "helm", NormalCode: "cap", UberCode: "xap", UltraCode: "uap"},
	307: {Code: "skp", Name: "Skull Cap", Type: "helm", NormalCode: "skp", UberCode: "xkp", UltraCode: "ukp"},
	308: {Code: "hlm", Name: "Helm", Type: "helm", NormalCode: "hlm", UberCode: "xlm", UltraCode: "ulm"},
	309: {Code: "fhl", Name: "Full Helm", Type: "helm", NormalCode: "fhl", UberCode: "xhl", UltraCode: "uhl"},
	310: {Code: "ghm", Name: "Great Helm", Type: "helm", NormalCode: "ghm", UberCode: "xhm", UltraCode: "uhm"},
	311: {Code: "crn", Name: "Crown", Type: "helm", NormalCode: "crn", UberCode: "xrn", UltraCode: "urn"},
	312: {Code: "msk", Name: "Mask", Type: "helm", NormalCode: "msk", UberCode: "xsk", UltraCode: "usk"},
	313: {Code: "qui", Name: "Quilted Armor", Type: "tors", NormalCode: "qui", UberCode: "xui", UltraCode: "uui"},
	314: {Code: "lea", Name: "Leather Armor", Type: "tors", NormalCode: "lea", UberCode: "xea", UltraCode: "uea"},
	315: {Code: "hla", Name: "Hard Leather Armor", Type: "tors", NormalCode: "hla", UberCode: "xla", UltraCode: "ula"},
	316: {Code: "stu", Name: "Studded Leather", Type: "tors", NormalCode: "stu", UberCode: "xtu", UltraCode: "utu", Width: 2, Height: 3},
	317: {Code: "rng", Name: "Ring Mail", Type: "tors", NormalCode: "rng", UberCode: "xng", UltraCode: "ung"},
	318: {Code: "scl", Name: "Scale Mail", Type: "tors", NormalCode: "scl", UberCode: "xcl", UltraCode: "ucl"},
	319: {Code: "chn", Name: "Chain Mail", Type: "tors", NormalCode: "chn", UberCode: "xhn", UltraCode: "uhn"},
	320: {Code: "brs", Name: "Breast Plate", Type: "tors", NormalCode: "brs", UberCode: "xrs", UltraCode: "urs"},
	321: {Code: "spl", Name: "Splint Mail", Type: "tors", NormalCode: "spl", UberCode: "xpl", UltraCode: "upl"},
	322: {Code: "plt", Name: "Plate Mail", Type: "tors", NormalCode: "plt", UberCode: "xlt", UltraCode: "ult"},
	323: {Code: "fld", Name: "Field Plate", Type: "tors", NormalCode: "fld", UberCode: "xld", UltraCode: "uld"},
	324: {Code: "gth", Name: "Gothic Plate", Type: "tors", NormalCode: "gth", UberCode: "xth", UltraCode: "uth"},
	325: {Code: "ful", Name: "Full Plate Mail", Type: "tors", NormalCode: "ful", UberCode: "xul", UltraCode: "uul"},
	326: {Code: "aar", Name: "Ancient Armor", Type: "tors", NormalCode: "aar", UberCode: "xar", UltraCode: "uar"},
	327: {Code: "ltp", Name: "Light Plate", Type: "tors", NormalCode: "ltp", UberCode: "xtp", UltraCode: "utp"},
	328: {Code: "buc", Name: "Buckler", Type: "shie", NormalCode: "buc", UberCode: "xuc", UltraCode: "uuc"},
	329: {Code: "sml", Name: "Small Shield", Type: "shie", NormalCode: "sml", UberCode: "xml", UltraCode: "uml"},
	330: {Code: "lrg", Name: "Large Shield", Type: "shie", NormalCode: "lrg", UberCode: "xrg", UltraCode: "urg"},
	331: {Code: "kit", Name: "Kite Shield", Type: "shie", NormalCode: "kit", UberCode: "xit", UltraCode: "uit"},
	332: {Code: "tow", Name: "Tower Shield", Type: "shie", NormalCode: "tow", UberCode: "xow", UltraCode: "uow"},
	333: {Code: "gts", Name: "Gothic Shield", Type: "shie", NormalCode: "gts", UberCode: "xts", UltraCode: "uts"},
	334: {Code: "lgl", Name: "Leather Gloves", Type: "glov", NormalCode: "lgl", UberCode: "xlg", UltraCode: "ulg"},
	335: {Code: "vgl", Name: "Heavy Gloves", Type: "glov", NormalCode: "vgl", UberCode: "xvg", UltraCode: "uvg"},
	336: {Code: "mgl", Name: "Chain Gloves", Type: "glov", NormalCode: "mgl", UberCode: "xmg", UltraCode: "umg"},
	337: {Code: "tgl", Name: "Light Gauntlets", Type: "glov", NormalCode: "tgl", UberCode: "xtg", UltraCode: "utg"},
	338: {Code: "hgl", Name: "Gauntlets", Type: "glov", NormalCode: "hgl", UberCode: "xhg", UltraCode: "uhg"},
	339: {Code: "lbt", Name: "Boots", Type: "boot", NormalCode: "lbt", UberCode: "xlb", UltraCode: "ulb"},
	340: {Code: "vbt", Name: "Heavy Boots", Type: "boot", NormalCode: "vbt", UberCode: "xvb", UltraCode: "uvb"},
	341: {Code: "mbt", Name: "Chain Boots", Type: "boot", NormalCode: "mbt", UberCode: "xmb", UltraCode: "umb"},
	342: {Code: "tbt", Name: "Light Plated Boots", Type: "boot", NormalCode: "tbt", UberCode: "xtb", UltraCode: "utb"},
	343: {Code: "hbt", Name: "Greaves", Type: "boot", NormalCode: "hbt", UberCode: "xhb", UltraCode: "uhb"},
	344: {Code: "lbl", Name: "Sash", Type: "belt", NormalCode: "lbl", UberCode: "zlb", UltraCode: "ulc"},
	345: {Code: "vbl", Name: "Light Belt", Type: "belt", NormalCode: "vbl", UberCode: "zvb", UltraCode: "uvc"},
	346: {Code: "mbl", Name: "Belt", Type: "belt", NormalCode: "mbl", UberCode: "zmb", UltraCode: "umc"},
	347: {Code: "tbl", Name: "Heavy Belt", Type: "belt", NormalCode: "tbl", UberCode: "ztb", UltraCode: "utc"},
	348: {Code: "hbl", Name: "Plated Belt", Type: "belt", NormalCode: "hbl", UberCode: "zhb", UltraCode: "uhc"},
	349: {Code: "bhm", Name: "Bone Helm", Type: "helm", NormalCode: "bhm", UberCode: "xh9", UltraCode: "uh9"},
	350: {Code: "bsh", Name: "Bone Shield", Type: "shie", NormalCode: "bsh", UberCode: "xsh", UltraCode: "ush"},
	351: {Code: "spk", Name: "Spiked Shield", Type: "shie", NormalCode: "spk", UberCode: "xpk", UltraCode: "upk"},
	352: {Code: "xap", Name: "War Hat", Type: "helm", NormalCode: "cap", UberCode: "xap", UltraCode: "uap"},
	353: {Code: "xkp", Name: "Sallet", Type: "helm", NormalCode: "skp", UberCode: "xkp", UltraCode: "ukp"},
	354: {Code: "xlm", Name: "Casque", Type: "helm", NormalCode: "hlm", UberCode: "xlm", UltraCode: "ulm"},
	355: {Code: "xhl", Name: "Basinet", Type: "helm", NormalCode: "fhl", UberCode: "xhl", UltraCode: "uhl"},
	356: {Code: "xhm", Name: "Winged Helm", Type: "helm", NormalCode: "ghm", UberCode: "xhm", UltraCode: "uhm"},
	357: {Code: "xrn", Name: "Grand Crown", Type: "helm", NormalCode: "crn", UberCode: "xrn", UltraCode: "urn"},
	358: {Code: "xsk", Name: "Death Mask", Type: "helm", NormalCode: "msk", UberCode: "xsk", UltraCode: "usk"},
	359: {Code: "xui", Name: "Ghost Armor", Type: "tors", NormalCode: "qui", UberCode: "xui", UltraCode: "uui"},
	360: {Code: "xea", Name: "Serpentskin Armor", Type: "tors", NormalCode: "lea", UberCode: "xea", UltraCode: "uea"},
	361: {Code: "xla", Name: "Demonhide Armor", Type: "tors", NormalCode: "hla", UberCode: "xla", UltraCode: "ula"},
	362: {Code: "xtu", Name: "Trellised Armor", Type: "tors", NormalCode: "stu", UberCode: "xtu", UltraCode: "utu"},
	363: {Code: "xng", Name: "Linked Mail", Type: "tors", NormalCode: "rng", UberCode: "xng", UltraCode: "ung"},
	364: {Code: "xcl", Name: "Tigulated Mail", Type: "tors", NormalCode: "scl", UberCode: "xcl", UltraCode: "ucl"},
	365: {Code: "xhn", Name: "Mesh Armor", Type: "tors", NormalCode: "chn", UberCode: "xhn", UltraCode: "uhn"},
	366: {Code: "xrs", Name: "Cuirass", Type: "tors", NormalCode: "brs", UberCode: "xrs", UltraCode: "urs"},
	367: {Code: "xpl", Name: "Russet Armor", Type: "tors", NormalCode: "spl", UberCode: "xpl", UltraCode: "upl"},
	368: {Code: "xlt", Name: "Templar Coat", Type: "tors", NormalCode: "plt", UberCode: "xlt", UltraCode: "ult"},
	369: {Code: "xld", Name: "Sharktooth Armor", Type: "tors", NormalCode: "fld", UberCode: "xld", UltraCode: "uld"},
	370: {Code: "xth", Name: "Embossed Plate", Type: "tors", NormalCode: "gth", UberCode: "xth", UltraCode: "uth"},
	371: {Code: "xul", Name: "Chaos Armor", Type: "tors", NormalCode: "ful", UberCode: "xul", UltraCode: "uul"},
	372: {Code: "xar", Name: "Ornate Armor", Type: "tors", NormalCode: "aar", UberCode: "xar", UltraCode: "uar"},
	373: {Code: "xtp", Name: "Mage Plate", Type: "tors", NormalCode: "ltp", UberCode: "xtp", UltraCode: "utp"},
	374: {Code: "xuc", Name: "Defender", Type: "shie", NormalCode: "buc", UberCode: "xuc", UltraCode: "uuc"},
	375: {Code: "xml", Name: "Round Shield", Type: "shie", NormalCode: "sml", UberCode: "xml", UltraCode: "uml"},
	376: {Code: "xrg", Name: "Scutum", Type: "shie", NormalCode: "lrg", UberCode: "xrg", UltraCode: "urg"},
	377: {Code: "xit", Name: "Dragon Shield", Type: "shie", NormalCode: "kit", UberCode: "xit", UltraCode: "uit"},
	378: {Code: "xow", Name: "Pavise", Type: "shie", NormalCode: "tow", UberCode: "xow", UltraCode: "uow"},
	379: {Code: "xts", Name: "Ancient Shield", Type: "shie", NormalCode: "gts", UberCode: "xts", UltraCode: "uts"},
	380: {Code: "xlg", Name: "Demonhide Gloves", Type: "glov", NormalCode: "lgl", UberCode: "xlg", UltraCode: "ulg"},
	381: {Code: "xvg", Name: "Sharkskin Gloves", Type: "glov", NormalCode: "vgl", UberCode: "xvg", UltraCode: "uvg"},
	382: {Code: "xmg", Name: "Heavy Bracers", Type: "glov", NormalCode: "mgl", UberCode: "xmg", UltraCode: "umg"},
	383: {Code: "xtg", Name: "Battle Gauntlets", Type: "glov", NormalCode: "tgl", UberCode: "xtg", UltraCode: "utg"},
	384: {Code: "xhg", Name: "War Gauntlets", Type: "glov", NormalCode: "hgl", UberCode: "xhg", UltraCode: "uhg"},
	385: {Code: "xlb", Name: "Demonhide Boots", Type: "boot", NormalCode: "lbt", UberCode: "xlb", UltraCode: "ulb"},
	386: {Code: "xvb", Name: "Sharkskin Boots", Type: "boot", NormalCode: "vbt", UberCode: "xvb", UltraCode: "uvb"},
	387: {Code: "xmb", Name: "Mesh Boots", Type: "boot", NormalCode: "mbt", UberCode: "xmb", UltraCode: "umb"},
	388: {Code: "xtb", Name: "Battle Boots", Type: "boot", NormalCode: "tbt", UberCode: "xtb", UltraCode: "utb"},
	389: {Code: "xhb", Name: "War Boots", Type: "boot", NormalCode: "hbt", UberCode: "xhb", UltraCode: "uhb"},
	390: {Code: "zlb", Name: "Demonhide Sash", Type: "belt", NormalCode: "lbl", UberCode: "zlb", UltraCode: "ulc"},
	391: {Code: "zvb", Name: "Sharkskin Belt", Type: "belt", NormalCode: "vbl", UberCode: "zvb", UltraCode: "uvc"},
	392: {Code: "zmb", Name: "Mesh Belt", Type: "belt", NormalCode: "mbl", UberCode: "zmb", UltraCode: "umc"},
	393: {Code: "ztb", Name: "Battle Belt", Type: "belt", NormalCode: "tbl", UberCode: "ztb", UltraCode: "utc"},
	394: {Code: "zhb", Name: "War Belt", Type: "belt", NormalCode: "hbl", UberCode: "zhb", UltraCode: "uhc"},
	395: {Code: "xh9", Name: "Grim Helm", Type: "helm", NormalCode: "bhm", UberCode: "xh9", UltraCode: "uh9"},
	396: {Code: "xsh", Name: "Grim Shield", Type: "shie", NormalCode: "bsh", UberCode: "xsh", UltraCode: "ush"},
	397: {Code: "xpk", Name: "Barbed Shield", Type: "shie", NormalCode: "spk", UberCode: "xpk", UltraCode: "upk"},
	398: {Code: "dr1", Name: "Wolf Head", Type: "pelt", NormalCode: "dr1", UberCode: "dr6", UltraCode: "drb"},
	399: {Code: "dr2", Name: "Hawk Helm", Type: "pelt", NormalCode: "dr2", UberCode: "dr7", UltraCode: "drc"},
	400: {Code: "dr3", Name: "Antlers", Type: "pelt", NormalCode: "dr3", UberCode: "dr8", UltraCode: "drd"},
	401: {Code: "dr4", Name: "Falcon Mask", Type: "pelt", NormalCode: "dr4", UberCode: "dr9", UltraCode: "dre"},
	402: {Code: "dr5", Name: "Spirit Mask", Type: "pelt", NormalCode: "dr5", UberCode: "dra", UltraCode: "drf"},
	403: {Code: "ba1", Name: "Jawbone Cap", Type: "phlm", NormalCode: "ba1", UberCode: "ba6", UltraCode: "bab"},
	404: {Code: "ba2", Name: "Fanged Helm", Type: "phlm", NormalCode: "ba2", UberCode: "ba7", UltraCode: "bac"},
	405: {Code: "ba3", Name: "Horned Helm", Type: "phlm", NormalCode: "ba3", UberCode: "ba8", UltraCode: "bad"},
	406: {Code: "ba4", Name: "Assault Helmet", Type: "phlm", NormalCode: "ba4", UberCode: "ba9", UltraCode: "bae"},
	407: {Code: "ba5", Name: "Avenger Guard", Type: "phlm", NormalCode: "ba5", UberCode: "baa", UltraCode: "baf"},
	408: {Code: "pa1", Name: "Targe", Type: "ashd", NormalCode: "pa1", UberCode: "pa6", UltraCode: "pab"},
	409: {Code: "pa2", Name: "Rondache", Type: "ashd", NormalCode: "pa2", UberCode: "pa7", UltraCode: "pac"},
	410: {Code: "pa3", Name: "Heraldic Shield", Type: "ashd", NormalCode: "pa3", UberCode: "pa8", UltraCode: "pad"},
	411: {Code: "pa4", Name: "Aerin Shield", Type: "ashd", NormalCode: "pa4", UberCode: "pa9", UltraCode: "pae"},
	412: {Code: "pa5", Name: "Crown Shield", Type: "ashd", NormalCode: "pa5", UberCode: "paa", UltraCode: "paf"},
	413: {Code: "ne1", Name: "Preserved Head", Type: "head", NormalCode: "ne1", UberCode: "ne6", UltraCode: "neb"},
	414: {Code: "ne2", Name: "Zombie Head", Type: "head", NormalCode: "ne2", UberCode: "ne7", UltraCode: "neg"},
	415: {Code: "ne3", Name: "Unraveller Head", Type: "head", NormalCode: "ne3", UberCode: "ne8", UltraCode: "ned"},
	416: {Code: "ne4", Name: "Gargoyle Head", Type: "head", NormalCode: "ne4", UberCode: "ne9", UltraCode: "nee"},
	417: {Code: "ne5", Name: "Demon Head", Type: "head", NormalCode: "ne5", UberCode: "nea", UltraCode: "nef"},
	418: {Code: "ci0", Name: "Circlet", Type: "circ", NormalCode: "ci0", UberCode: "ci2", UltraCode: "ci3"},
	419: {Code: "ci1", Name: "Coronet", Type: "circ", NormalCode: "ci1", UberCode: "ci2", UltraCode: "ci3"},
	420: {Code: "ci2", Name: "Tiara", Type: "circ", NormalCode: "ci1", UberCode: "ci2", UltraCode: "ci3"},
	421: {Code: "ci3", Name: "Diadem", Type: "circ", NormalCode: "ci1", UberCode: "ci2", UltraCode: "ci3"},
	422: {Code: "uap", Name: "Shako", Type: "helm", NormalCode: "cap", UberCode: "xap", UltraCode: "uap"},
	423: {Code: "ukp", Name: "Hydraskull", Type: "helm", NormalCode: "skp", UberCode: "xkp", UltraCode: "ukp"},
	424: {Code: "ulm", Name: "Armet", Type: "helm", NormalCode: "hlm", UberCode: "xlm", UltraCode: "ulm"},
	425: {Code: "uhl", Name: "Giant Conch", Type: "helm", NormalCode: "fhl", UberCode: "xhl", UltraCode: "uhl"},
	426: {Code: "uhm", Name: "Spired Helm", Type: "helm", NormalCode: "ghm", UberCode: "xhm", UltraCode: "uhm"},
	427: {Code: "urn", Name: "Corona", Type: "helm", NormalCode: "crn", UberCode: "xrn", UltraCode: "urn"},
	428: {Code: "usk", Name: "Demonhead", Type: "helm", NormalCode: "msk", UberCode: "xsk", UltraCode: "usk"},
	429: {Code: "uui", Name: "Dusk Shroud", Type: "tors", NormalCode: "qui", UberCode: "xui", UltraCode: "uui"},
	430: {Code: "uea", Name: "Wyrmhide", Type: "tors", NormalCode: "lea", UberCode: "xea", UltraCode: "uea"},
	431: {Code: "ula", Name: "Scarab Husk", Type: "tors", NormalCode: "hla", UberCode: "xla", UltraCode: "ula"},
	432: {Code: "utu", Name: "Wire Fleece", Type: "tors", NormalCode: "stu", UberCode: "xtu", UltraCode: "utu"},
	433: {Code: "ung", Name: "Diamond Mail", Type: "tors", NormalCode: "rng", UberCode: "xng", UltraCode: "ung"},
	434: {Code: "ucl", Name: "Loricated Mail", Type: "tors", NormalCode: "scl", UberCode: "xcl", UltraCode: "ucl"},
	435: {Code: "uhn", Name: "Boneweave", Type: "tors", NormalCode: "chn", UberCode: "xhn", UltraCode: "uhn"},
	436: {Code: "urs", Name: "Great Hauberk", Type: "tors", NormalCode: "brs", UberCode: "xrs", UltraCode: "urs"},
	437: {Code: "upl", Name: "Balrog Skin", Type: "tors", NormalCode: "spl", UberCode: "xpl", UltraCode: "upl"},
	438: {Code: "ult", Name: "Hellforge Plate", Type: "tors", NormalCode: "plt", UberCode: "xlt", UltraCode: "ult"},
	439: {Code: "uld", Name: "Kraken Shell", Type: "tors", NormalCode: "fld", UberCode: "xld", UltraCode: "uld"},
	440: {Code: "uth", Name: "Lacquered Plate", Type: "tors", NormalCode: "gth", UberCode: "xth", UltraCode: "uth"},
	441: {Code: "uul", Name: "Shadow Plate", Type: "tors", NormalCode: "ful", UberCode: "xul", UltraCode: "uul"},
	442: {Code: "uar", Name: "Sacred Armor", Type: "tors", NormalCode: "aar", UberCode: "xar", UltraCode: "uar"},
	443: {Code: "utp", Name: "Archon Plate", Type: "tors", NormalCode: "ltp", UberCode: "xtp", UltraCode: "utp"},
	444: {Code: "uuc", Name: "Heater", Type: "shie", NormalCode: "buc", UberCode: "xuc", UltraCode: "uuc"},
	445: {Code: "uml", Name: "Luna", Type: "shie", NormalCode: "sml", UberCode: "xml", UltraCode: "uml"},
	446: {Code: "urg", Name: "Hyperion", Type: "shie", NormalCode: "lrg", UberCode: "xrg", UltraCode: "urg"},
	447: {Code: "uit", Name: "Monarch", Type: "shie", NormalCode: "kit", UberCode: "xit", UltraCode: "uit"},
	448: {Code: "uow", Name: "Aegis", Type: "shie", NormalCode: "tow", UberCode: "xow", UltraCode: "uow"},
	449: {Code: "uts", Name: "Ward", Type: "shie", NormalCode: "gts", UberCode: "xts", UltraCode: "uts"},
	450: {Code: "ulg", Name: "Bramble Mitts", Type: "glov", NormalCode: "lgl", UberCode: "xlg", UltraCode: "ulg"},
	451: {Code: "uvg", Name: "Vampirebone Gloves", Type: "glov", NormalCode: "vgl", UberCode: "xvg", UltraCode: "uvg"},
	452: {Code: "umg", Name: "Vambraces", Type: "glov", NormalCode: "mgl", UberCode: "xmg", UltraCode: "umg"},
	453: {Code: "utg", Name: "Crusader Gauntlets", Type: "glov", NormalCode: "tgl", UberCode: "xtg", UltraCode: "utg"},
	454: {Code: "uhg", Name: "Ogre Gauntlets", Type: "glov", NormalCode: "hgl", UberCode: "xhg", UltraCode: "uhg"},
	455: {Code: "ulb", Name: "Wyrmhide Boots", Type: "boot", NormalCode: "lbt", UberCode: "xlb", UltraCode: "ulb"},
	456: {Code: "uvb", Name: "Scarabshell Boots", Type: "boot", NormalCode: "vbt", UberCode: "xvb", UltraCode: "uvb"},
	457: {Code: "umb", Name: "Boneweave Boots", Type: "boot", NormalCode: "mbt", UberCode: "xmb", UltraCode: "umb"},
	458: {Code: "utb", Name: "Mirrored Boots", Type: "boot", NormalCode: "tbt", UberCode: "xtb", UltraCode: "utb"},
	459: {Code: "uhb", Name: "Myrmidon Greaves", Type: "boot", NormalCode: "hbt", UberCode: "xhb", UltraCode: "uhb"},
	460: {Code: "ulc", Name: "Spiderweb Sash", Type: "belt", NormalCode: "lbl", UberCode: "zlb", UltraCode: "ulc"},
	461: {Code: "uvc", Name: "Vampirefang Belt", Type: "belt", NormalCode: "vbl", UberCode: "zvb", UltraCode: "uvc"},
	462: {Code: "umc", Name: "Mithril Coil", Type: "belt", NormalCode: "mbl", UberCode: "zmb", UltraCode: "umc"},
	463: {Code: "utc", Name: "Troll Belt", Type: "belt", NormalCode: "tbl", UberCode: "ztb", UltraCode: "utc"},
	464: {Code: "uhc", Name: "Colossus Girdle", Type: "belt", NormalCode: "hbl", UberCode: "zhb", UltraCode: "uhc"},
	465: {Code: "uh9", Name: "Bone Visage", Type: "helm", NormalCode: "bhm", UberCode: "xh9", UltraCode: "uh9"},
	466: {Code: "ush", Name: "Troll Nest", Type: "shie", NormalCode: "bsh", UberCode: "xsh", UltraCode: "ush"},
	467: {Code: "upk", Name: "Blade Barrier", Type: "shie", NormalCode: "spk", UberCode: "xpk", UltraCode: "upk"},
	468: {Code: "dr6", Name: "Alpha Helm", Type: "pelt", NormalCode: "dr1", UberCode: "dr6", UltraCode: "drb"},
	469: {Code: "dr7", Name: "Griffon Headress", Type: "pelt", NormalCode: "dr2", UberCode: "dr7", UltraCode: "drc"},
	470: {Code: "dr8", Name: "Hunter's Guise", Type: "pelt", NormalCode: "dr3", UberCode: "dr8", UltraCode: "drd"},
	471: {Code: "dr9", Name: "Sacred Feathers", Type: "pelt", NormalCode: "dr4", UberCode: "dr9", UltraCode: "dre"},
	472: {Code: "dra", Name: "Totemic Mask", Type: "pelt", NormalCode: "dr5", UberCode: "dra", UltraCode: "drf"},
	473: {Code: "ba6", Name: "Jawbone Visor", Type: "phlm", NormalCode: "ba1", UberCode: "ba6", UltraCode: "bab"},
	474: {Code: "ba7", Name: "Lion Helm", Type: "phlm", NormalCode: "ba2", UberCode: "ba7", UltraCode: "bac"},
	475: {Code: "ba8", Name: "Rage Mask", Type: "phlm", NormalCode: "ba3", UberCode: "ba8", UltraCode: "bad"},
	476: {Code: "ba9", Name: "Savage Helmet", Type: "phlm", NormalCode: "ba4", UberCode: "ba9", UltraCode: "bae"},
	477: {Code: "baa", Name: "Slayer Guard", Type: "phlm", NormalCode: "ba5", UberCode: "baa", UltraCode: "baf"},
	478: {Code: "pa6", Name: "Akaran Targe", Type: "ashd", NormalCode: "pa1", UberCode: "pa6", UltraCode: "pab"},
	479: {Code: "pa7", Name: "Akaran Rondache", Type: "ashd", NormalCode: "pa2", UberCode: "pa7", UltraCode: "pac"},
	480: {Code: "pa8", Name: "Protector Shield", Type: "ashd", NormalCode: "pa3", UberCode: "pa8", UltraCode: "pad"},
	481: {Code: "pa9", Name: "Gilded Shield", Type: "ashd", NormalCode: "pa4", UberCode: "pa9", UltraCode: "pae"},
	482: {Code: "paa", Name: "Royal Shield", Type: "ashd", NormalCode: "pa5", UberCode: "paa", UltraCode: "paf"},
	483: {Code: "ne6", Name: "Mummified Trophy", Type: "head", NormalCode: "ne1", UberCode: "ne6", UltraCode: "neb"},
	484: {Code: "ne7", Name: "Fetish Trophy", Type: "head", NormalCode: "ne2", UberCode: "ne7", UltraCode: "neg"},
	485: {Code: "ne8", Name: "Sexton Trophy", Type: "head", NormalCode: "ne3", UberCode: "ne8", UltraCode: "ned"},
	486: {Code: "ne9", Name: "Cantor Trophy", Type: "head", NormalCode: "ne4", UberCode: "ne9", UltraCode: "nee"},
	487: {Code: "nea", Name: "Heirophant Trophy", Type: "head", NormalCode: "ne5", UberCode: "nea", UltraCode: "nef"},
	488: {Code: "drb", Name: "Blood Spirit", Type: "pelt", NormalCode: "dr1", UberCode: "dr6", UltraCode: "drb"},
	489: {Code: "drc", Name: "Sun Spirit", Type: "pelt", NormalCode: "dr2", UberCode: "dr7", UltraCode: "drc"},
	490: {Code: "drd", Name: "Earth Spirit", Type: "pelt", NormalCode: "dr3", UberCode: "dr8", UltraCode: "drd"},
	491: {Code: "dre", Name: "Sky Spirit", Type: "pelt", NormalCode: "dr4", UberCode: "dr9", UltraCode: "dre"},
	492: {Code: "drf", Name: "Dream Spirit", Type: "pelt", NormalCode: "dr5", UberCode: "dra", UltraCode: "drf"},
	493: {Code: "bab", Name: "Carnage Helm", Type: "phlm", NormalCode: "ba1", UberCode: "ba6", UltraCode: "bab"},
	494: {Code: "bac", Name: "Fury Visor", Type: "phlm", NormalCode: "ba2", UberCode: "ba7", UltraCode: "bac"},
	495: {Code: "bad", Name: "Destroyer Helm", Type: "phlm", NormalCode: "ba3", UberCode: "ba8", UltraCode: "bad"},
	496: {Code: "bae", Name: "Conqueror Crown", Type: "phlm", NormalCode: "ba4", UberCode: "ba9", UltraCode: "bae"},
	497: {Code: "baf", Name: "Guardian Crown", Type: "phlm", NormalCode: "ba5", UberCode: "baa", UltraCode: "baf"},
	498: {Code: "pab", Name: "Sacred Targe", Type: "ashd", NormalCode: "pa1", UberCode: "pa6", UltraCode: "pab"},
	499: {Code: "pac", Name: "Sacred Rondache", Type: "ashd", NormalCode: "pa2", UberCode: "pa7", UltraCode: "pac"},
	500: {Code: "pad", Name: "Ancient Shield", Type: "ashd", NormalCode: "pa3", UberCode: "pa8", UltraCode: "pad"},
	501: {Code: "pae", Name: "Zakarum Shield", Type: "ashd", NormalCode: "pa4", UberCode: "pa9", UltraCode: "pae"},
	502: {Code: "paf", Name: "Vortex Shield", Type: "ashd", NormalCode: "pa5", UberCode: "paa", UltraCode: "paf"},
	503: {Code: "neb", Name: "Minion Skull", Type: "head", NormalCode: "ne1", UberCode: "ne6", UltraCode: "neb"},
	504: {Code: "neg", Name: "Hellspawn Skull", Type: "head", NormalCode: "ne2", UberCode: "ne7", UltraCode: "neg"},
	505: {Code: "ned", Name: "Overseer Skull", Type: "head", NormalCode: "ne3", UberCode: "ne8", UltraCode: "ned"},
	506: {Code: "nee", Name: "Succubus Skull", Type: "head", NormalCode: "ne4", UberCode: "ne9", UltraCode: "nee"},
	507: {Code: "nef", Name: "Bloodlord Skull", Type: "head", NormalCode: "ne5", UberCode: "nea", UltraCode: "nef"},
	508: {Code: "wa1", Name: "Old Book", Type: "grim", NormalCode: "wa1", UberCode: "wa6", UltraCode: "wab"},
	509: {Code: "wa2", Name: "Tome", Type: "grim", NormalCode: "wa2", UberCode: "wa7", UltraCode: "wac"},
	510: {Code: "wa3", Name: "Codex", Type: "grim", NormalCode: "wa3", UberCode: "wa8", UltraCode: "wad"},
	511: {Code: "wa4", Name: "Compendium", Type: "grim", NormalCode: "wa4", UberCode: "wa9", UltraCode: "wae"},
	512: {Code: "wa5", Name: "Grimoire", Type: "grim", NormalCode: "wa5", UberCode: "waa", UltraCode: "waf"},
	513: {Code: "wa6", Name: "Burnt Text", Type: "grim", NormalCode: "wa1", UberCode: "wa6", UltraCode: "wab"},
	514: {Code: "wa7", Name: "Dark Tome", Type: "grim", NormalCode: "wa2", UberCode: "wa7", UltraCode: "wac"},
	515: {Code: "wa8", Name: "Dark Codex", Type: "grim", NormalCode: "wa3", UberCode: "wa8", UltraCode: "wad"},
	516: {Code: "wa9", Name: "Possessed Compendium", Type: "grim", NormalCode: "wa4", UberCode: "wa9", UltraCode: "wae"},
	517: {Code: "waa", Name: "Possessed Grimoire", Type: "grim", NormalCode: "wa5", UberCode: "waa", UltraCode: "waf"},
	518: {Code: "wab", Name: "Forgotten Volume", Type: "grim", NormalCode: "wa1", UberCode: "wa6", UltraCode: "wab"},
	519: {Code: "wac", Name: "Occult Tome", Type: "grim", NormalCode: "wa2", UberCode: "wa7", UltraCode: "wac"},
	520: {Code: "wad", Name: "Occult Codex", Type: "grim", NormalCode: "wa3", UberCode: "wa8", UltraCode: "wad"},
	521: {Code: "wae", Name: "Blasphemous Compendium", Type: "grim", NormalCode: "wa4", UberCode: "wa9", UltraCode: "wae"},
	522: {Code: "waf", Name: "Blasphemous Grimoire", Type: "grim", NormalCode: "wa5", UberCode: "waa", UltraCode: "waf"},
	523: {Code: "elx", Name: "Elixir", Type: "elix", NormalCode: "", UberCode: "", UltraCode: ""},
	524: {Code: "hpo", Name: "Healing Potion", Type: "hpot", NormalCode: "", UberCode: "", UltraCode: ""},
	525: {Code: "mpo", Name: "Mana Potion", Type: "mpot", NormalCode: "", UberCode: "", UltraCode: ""},
	526: {Code: "hpf", Name: "Full Healing Potion", Type: "hpot", NormalCode: "", UberCode: "", UltraCode: ""},
	527: {Code: "mpf", Name: "Full Mana Potion", Type: "mpot", NormalCode: "", UberCode: "", UltraCode: ""},
	528: {Code: "vps", Name: "Stamina Potion", Type: "spot", NormalCode: "", UberCode: "", UltraCode: ""},
	529: {Code: "yps", Name: "Antidote Potion", Type: "apot", NormalCode: "", UberCode: "", UltraCode: ""},
	530: {Code: "rvs", Name: "Rejuvenation Potion", Type: "rpot", NormalCode: "", UberCode: "", UltraCode: ""},
	531: {Code: "rvl", Name: "Full Rejuvenation Potion", Type: "rpot", NormalCode: "", UberCode: "", UltraCode: ""},
	532: {Code: "wms", Name: "Thawing Potion", Type: "wpot", NormalCode: "", UberCode: "", UltraCode: ""},
	533: {Code: "tbk", Name: "Tome of Town Portal", Type: "book", NormalCode: "", UberCode: "", UltraCode: "", Width: 1, Height: 2},
	534: {Code: "ibk", Name: "Tome of Identify", Type: "book", NormalCode: "", UberCode: "", UltraCode: "", Width: 1, Height: 2},
	535: {Code: "amu", Name: "Amulet", Type: "amul", NormalCode: "", UberCode: "", UltraCode: ""},
	536: {Code: "vip", Name: "Amulet of the Viper", Type: "amul", NormalCode: "", UberCode: "", UltraCode: ""},
	537: {Code: "rin", Name: "Ring", Type: "ring", NormalCode: "", UberCode: "", UltraCode: ""},
	538: {Code: "gld", Name: "Gold", Type: "gold", NormalCode: "", UberCode: "", UltraCode: ""},
	539: {Code: "bks", Name: "Scroll of Inifuss", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	540: {Code: "bkd", Name: "Key to the Cairn Stones", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	541: {Code: "aqv", Name: "Arrows", Type: "bowq", NormalCode: "", UberCode: "", UltraCode: ""},
	542: {Code: "tch", Name: "Torch", Type: "torc", NormalCode: "", UberCode: "", UltraCode: ""},
	543: {Code: "cqv", Name: "Bolts", Type: "xboq", NormalCode: "", UberCode: "", UltraCode: ""},
	544: {Code: "tsc", Name: "Scroll of Town Portal", Type: "scro", NormalCode: "", UberCode: "", UltraCode: ""},
	545: {Code: "isc", Name: "Scroll of Identify", Type: "scro", NormalCode: "", UberCode: "", UltraCode: ""},
	546: {Code: "hrt", Name: "Heart", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	547: {Code: "brz", Name: "Brain", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	548: {Code: "jaw", Name: "Jawbone", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	549: {Code: "eyz", Name: "Eye", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	550: {Code: "hrn", Name: "Horn", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	551: {Code: "tal", Name: "Tail", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	552: {Code: "flg", Name: "Flag", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	553: {Code: "fng", Name: "Fang", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	554: {Code: "qll", Name: "Quill", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	555: {Code: "sol", Name: "Soul", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	556: {Code: "scz", Name: "Scalp", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	557: {Code: "spe", Name: "Spleen", Type: "body", NormalCode: "", UberCode: "", UltraCode: ""},
	558: {Code: "key", Name: "Key", Type: "key", NormalCode: "", UberCode: "", UltraCode: ""},
	559: {Code: "luv", Name: "The Black Tower Key", Type: "key", NormalCode: "", UberCode: "", UltraCode: ""},
	560: {Code: "xyz", Name: "Potion of Life", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	561: {Code: "j34", Name: "A Jade Figurine", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	562: {Code: "g34", Name: "The Golden Bird", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	563: {Code: "bbb", Name: "Lam Esen's Tome", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	564: {Code: "box", Name: "Horadric Cube", Type: "ques", NormalCode: "", UberCode: "", UltraCode: "", Width: 2, Height: 2},
	565: {Code: "tr1", Name: "Horadric Scroll", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	566: {Code: "mss", Name: "Mephisto's Soulstone", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	567: {Code: "ass", Name: "Book of Skill", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	568: {Code: "qey", Name: "Khalim's Eye", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	569: {Code: "qhr", Name: "Khalim's Heart", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	570: {Code: "qbr", Name: "Khalim's Brain", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	571: {Code: "ear", Name: "Ear", Type: "play", NormalCode: "", UberCode: "", UltraCode: ""},
	572: {Code: "gcv", Name: "Chipped Amethyst", Type: "gema", NormalCode: "", UberCode: "", UltraCode: ""},
	573: {Code: "gfv", Name: "Flawed Amethyst", Type: "gema", NormalCode: "", UberCode: "", UltraCode: ""},
	574: {Code: "gsv", Name: "Amethyst", Type: "gema", NormalCode: "", UberCode: "", UltraCode: ""},
	575: {Code: "gzv", Name: "Flawless Amethyst", Type: "gema", NormalCode: "", UberCode: "", UltraCode: ""},
	576: {Code: "gpv", Name: "Perfect Amethyst", Type: "gema", NormalCode: "", UberCode: "", UltraCode: ""},
	577: {Code: "gcy", Name: "Chipped Topaz", Type: "gemt", NormalCode: "", UberCode: "", UltraCode: ""},
	578: {Code: "gfy", Name: "Flawed Topaz", Type: "gemt", NormalCode: "", UberCode: "", UltraCode: ""},
	579: {Code: "gsy", Name: "Topaz", Type: "gemt", NormalCode: "", UberCode: "", UltraCode: ""},
	580: {Code: "gly", Name: "Flawless Topaz", Type: "gemt", NormalCode: "", UberCode: "", UltraCode: ""},
	581: {Code: "gpy", Name: "Perfect Topaz", Type: "gemt", NormalCode: "", UberCode: "", UltraCode: ""},
	582: {Code: "gcb", Name: "Chipped Sapphire", Type: "gems", NormalCode: "", UberCode: "", UltraCode: ""},
	583: {Code: "gfb", Name: "Flawed Sapphire", Type: "gems", NormalCode: "", UberCode: "", UltraCode: ""},
	584: {Code: "gsb", Name: "Sapphire", Type: "gems", NormalCode: "", UberCode: "", UltraCode: ""},
	585: {Code: "glb", Name: "Flawless Sapphire", Type: "gems", NormalCode: "", UberCode: "", UltraCode: ""},
	586: {Code: "gpb", Name: "Perfect Sapphire", Type: "gems", NormalCode: "", UberCode: "", UltraCode: ""},
	587: {Code: "gcg", Name: "Chipped Emerald", Type: "geme", NormalCode: "", UberCode: "", UltraCode: ""},
	588: {Code: "gfg", Name: "Flawed Emerald", Type: "geme", NormalCode: "", UberCode: "", UltraCode: ""},
	589: {Code: "gsg", Name: "Emerald", Type: "geme", NormalCode: "", UberCode: "", UltraCode: ""},
	590: {Code: "glg", Name: "Flawless Emerald", Type: "geme", NormalCode: "", UberCode: "", UltraCode: ""},
	591: {Code: "gpg", Name: "Perfect Emerald", Type: "geme", NormalCode: "", UberCode: "", UltraCode: ""},
	592: {Code: "gcr", Name: "Chipped Ruby", Type: "gemr", NormalCode: "", UberCode: "", UltraCode: ""},
	593: {Code: "gfr", Name: "Flawed Ruby", Type: "gemr", NormalCode: "", UberCode: "", UltraCode: ""},
	594: {Code: "gsr", Name: "Ruby", Type: "gemr", NormalCode: "", UberCode: "", UltraCode: ""},
	595: {Code: "glr", Name: "Flawless Ruby", Type: "gemr", NormalCode: "", UberCode: "", UltraCode: ""},
	596: {Code: "gpr", Name: "Perfect Ruby", Type: "gemr", NormalCode: "", UberCode: "", UltraCode: ""},
	597: {Code: "gcw", Name: "Chipped Diamond", Type: "gemd", NormalCode: "", UberCode: "", UltraCode: ""},
	598: {Code: "gfw", Name: "Flawed Diamond", Type: "gemd", NormalCode: "", UberCode: "", UltraCode: ""},
	599: {Code: "gsw", Name: "Diamond", Type: "gemd", NormalCode: "", UberCode: "", UltraCode: ""},
	600: {Code: "glw", Name: "Flawless Diamond", Type: "gemd", NormalCode: "", UberCode: "", UltraCode: ""},
	601: {Code: "gpw", Name: "Perfect Diamond", Type: "gemd", NormalCode: "", UberCode: "", UltraCode: ""},
	602: {Code: "hp1", Name: "Minor Healing Potion", Type: "hpot", NormalCode: "", UberCode: "", UltraCode: ""},
	603: {Code: "hp2", Name: "Light Healing Potion", Type: "hpot", NormalCode: "", UberCode: "", UltraCode: ""},
	604: {Code: "hp3", Name: "Healing Potion", Type: "hpot", NormalCode: "", UberCode: "", UltraCode: ""},
	605: {Code: "hp4", Name: "Greater Healing Potion", Type: "hpot", NormalCode: "", UberCode: "", UltraCode: ""},
	606: {Code: "hp5", Name: "Super Healing Potion", Type: "hpot", NormalCode: "", UberCode: "", UltraCode: ""},
	607: {Code: "mp1", Name: "Minor Mana Potion", Type: "mpot", NormalCode: "", UberCode: "", UltraCode: ""},
	608: {Code: "mp2", Name: "Light Mana Potion", Type: "mpot", NormalCode: "", UberCode: "", UltraCode: ""},
	609: {Code: "mp3", Name: "Mana Potion", Type: "mpot", NormalCode: "", UberCode: "", UltraCode: ""},
	610: {Code: "mp4", Name: "Greater Mana Potion", Type: "mpot", NormalCode: "", UberCode: "", UltraCode: ""},
	611: {Code: "mp5", Name: "Super Mana Potion", Type: "mpot", NormalCode: "", UberCode: "", UltraCode: ""},
	612: {Code: "skc", Name: "Chipped Skull", Type: "gemz", NormalCode: "", UberCode: "", UltraCode: ""},
	613: {Code: "skf", Name: "Flawed Skull", Type: "gemz", NormalCode: "", UberCode: "", UltraCode: ""},
	614: {Code: "sku", Name: "Skull", Type: "gemz", NormalCode: "", UberCode: "", UltraCode: ""},
	615: {Code: "skl", Name: "Flawless Skull", Type: "gemz", NormalCode: "", UberCode: "", UltraCode: ""},
	616: {Code: "skz", Name: "Perfect Skull", Type: "gemz", NormalCode: "", UberCode: "", UltraCode: ""},
	617: {Code: "hrb", Name: "Herb", Type: "herb", NormalCode: "", UberCode: "", UltraCode: ""},
	618: {Code: "cm1", Name: "Small Charm", Type: "scha", NormalCode: "", UberCode: "", UltraCode: "", Width: 1, Height: 1},
	619: {Code: "cm2", Name: "Large Charm", Type: "mcha", NormalCode: "", UberCode: "", UltraCode: "", Width: 1, Height: 2},
	620: {Code: "cm3", Name: "Grand Charm", Type: "lcha", NormalCode: "", UberCode: "", UltraCode: "", Width: 1, Height: 3},
	621: {Code: "rps", Name: "Small Red Potion", Type: "hpot", NormalCode: "", UberCode: "", UltraCode: ""},
	622: {Code: "rpl", Name: "Large Red Potion", Type: "hpot", NormalCode: "", UberCode: "", UltraCode: ""},
	623: {Code: "bps", Name: "Small Blue Potion", Type: "mpot", NormalCode: "", UberCode: "", UltraCode: ""},
	624: {Code: "bpl", Name: "Large Blue Potion", Type: "mpot", NormalCode: "", UberCode: "", UltraCode: ""},
	625: {Code: "r01", Name: "El Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: "", Width: 1, Height: 1},
	626: {Code: "r02", Name: "Eld Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	627: {Code: "r03", Name: "Tir Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	628: {Code: "r04", Name: "Nef Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	629: {Code: "r05", Name: "Eth Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	630: {Code: "r06", Name: "Ith Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	631: {Code: "r07", Name: "Tal Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	632: {Code: "r08", Name: "Ral Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	633: {Code: "r09", Name: "Ort Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	634: {Code: "r10", Name: "Thul Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	635: {Code: "r11", Name: "Amn Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	636: {Code: "r12", Name: "Sol Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	637: {Code: "r13", Name: "Shael Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	638: {Code: "r14", Name: "Dol Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	639: {Code: "r15", Name: "Hel Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	640: {Code: "r16", Name: "Io Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	641: {Code: "r17", Name: "Lum Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	642: {Code: "r18", Name: "Ko Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	643: {Code: "r19", Name: "Fal Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	644: {Code: "r20", Name: "Lem Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	645: {Code: "r21", Name: "Pul Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	646: {Code: "r22", Name: "Um Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	647: {Code: "r23", Name: "Mal Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	648: {Code: "r24", Name: "Ist Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	649: {Code: "r25", Name: "Gul Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	650: {Code: "r26", Name: "Vex Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	651: {Code: "r27", Name: "Ohm Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	652: {Code: "r28", Name: "Lo Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	653: {Code: "r29", Name: "Sur Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	654: {Code: "r30", Name: "Ber Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	655: {Code: "r31", Name: "Jah Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	656: {Code: "r32", Name: "Cham Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	657: {Code: "r33", Name: "Zod Rune", Type: "rune", NormalCode: "", UberCode: "", UltraCode: ""},
	658: {Code: "jew", Name: "Jewel", Type: "jewl", NormalCode: "", UberCode: "", UltraCode: ""},
	659: {Code: "ice", Name: "Malah's Potion", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	660: {Code: "0sc", Name: "Scroll of Knowledge", Type: "scro", NormalCode: "", UberCode: "", UltraCode: ""},
	661: {Code: "tr2", Name: "Scroll of Resistance", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	662: {Code: "pk1", Name: "Key of Terror", Type: "ques", NormalCode: "", UberCode: "", UltraCode: "", Width: 1, Height: 1},
	663: {Code: "pk2", Name: "Key of Hate", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	664: {Code: "pk3", Name: "Key of Destruction", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	665: {Code: "dhn", Name: "Diablo's Horn", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	666: {Code: "bey", Name: "Baal's Eye", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	667: {Code: "mbr", Name: "Mephisto's Brain", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	668: {Code: "toa", Name: "Token of Absolution", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	669: {Code: "tes", Name: "Twisted Essence of Suffering", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	670: {Code: "ceh", Name: "Charged Essense of Hatred", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	671: {Code: "bet", Name: "Burning Essence of Terror", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	672: {Code: "fed", Name: "Festering Essence of Destruction", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	673: {Code: "std", Name: "Standard of Heroes", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	674: {Code: "xa1", Name: "Western Worldstone Shard", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	675: {Code: "xa2", Name: "Eastern Worldstone Shard", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	676: {Code: "xa3", Name: "Southern Worldstone Shard", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	677: {Code: "xa4", Name: "Deep Worldstone Shard", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	678: {Code: "xa5", Name: "Northern Worldstone Shard", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	679: {Code: "ua1", Name: "Uber Ancient Summon Material Act 1", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	680: {Code: "ua2", Name: "Uber Ancient Summon Material Act 2", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	681: {Code: "ua3", Name: "Uber Ancient Summon Material Act 3", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	682: {Code: "ua4", Name: "Uber Ancient Summon Material Act 4", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	683: {Code: "ua5", Name: "Uber Ancient Summon Material Act5", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	684: {Code: "um1", Name: "Uber Ancient Upgrade Material  Fire", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	685: {Code: "um2", Name: "Uber Ancient Upgrade Material Poison", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	686: {Code: "um3", Name: "Uber Ancient Upgrade Material  Cold", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	687: {Code: "um4", Name: "Uber Ancient Upgrade Material Physical", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	688: {Code: "um5", Name: "Uber Ancient Upgrade Material Lightning", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	689: {Code: "um6", Name: "Uber Ancient Upgrade Material Magic", Type: "ques", NormalCode: "", UberCode: "", UltraCode: ""},
	690: {Code: "cjw", Name: "Colossal Jewel", Type: "cjwl", NormalCode: "", UberCode: "", UltraCode: ""},
	691: {Code: "cs2", Name: "Crafted Sunder Charm", Type: "csch", NormalCode: "", UberCode: "", UltraCode: ""},
}
