const messages: Record<string, string> = {
  cow_scope_unsupported: "Cow-Setup unterstützt nur MrBones als Nekromant auf Hölle bei 1280 × 720 im Rogue Encampment.",
  cow_cube_missing: "Der Horadrimwürfel fehlt im persönlichen Inventar.",
  cow_cube_ambiguous: "Der Horadrimwürfel konnte nicht eindeutig im persönlichen Inventar bestätigt werden.",
  cow_cube_unprotected: "Alle vier Inventarfelder des Horadrimwürfels müssen gesperrt sein.",
  cow_cube_not_empty: "Der Horadrimwürfel muss vor dem Cow-Run leer sein.",
  cow_existing_leg: "Ein altes Wirt’s Leg ist sichtbar. Entferne es vor dem Cow-Run manuell.",
  cow_inventory_space_missing: "Es fehlt gleichzeitig freier Platz für Wirt’s Leg und ein zusätzliches Stadtportalbuch.",
  cow_return_portal_unavailable: "Für die sichere Rückkehr fehlt ein verwendbares Stadtportalbuch oder die Town-Portal-Bindung.",
  cow_combat_skill_missing: "Eine benötigte Bindung für Teleport, Amplify Damage, Corpse Explosion oder Bone Spear fehlt.",
  run_capability_missing: "Eine benötigte Cow-Route oder Stadtfunktion fehlt.",
  cow_wirt_interaction_failed: "Wirts Körper konnte nicht sicher geöffnet werden.",
  cow_wirt_hover_failed: "Wirts Körper wurde unter dem Mauszeiger nicht bestätigt.",
  cow_wirt_approach_failed: "Wirts Körper konnte nicht sicher erreicht werden.",
  cow_wirt_input_failed: "Der Klick auf Wirts Körper konnte nicht gesendet werden.",
  cow_wirt_pin_changed: "Der gebundene Körper von Wirt hat sich während der Annäherung geändert.",
  cow_wirt_state_invalid: "Wirts Körper war nicht mehr in einem sicher auswertbaren Spielzustand.",
  cow_wirt_unavailable: "Wirts Körper konnte innerhalb des Zeitfensters nicht bestätigt werden.",
  cow_leg_spawn_failed: "Nach der begrenzten Wirt-Interaktion erschien kein eindeutiges frisches Bein.",
  cow_leg_spawn_ambiguous: "Mehr als ein neues Bein erschien; der Bot hat sicher abgebrochen.",
  cow_leg_pickup_failed: "Das frische Bein konnte nicht sicher aufgenommen werden.",
  cow_leg_pickup_unconfirmed: "Die gebundene Bein-UnitID wurde im persönlichen Inventar nicht bestätigt.",
  cow_return_portal_failed: "Die sichere Rückkehr ins Rogue Encampment ist fehlgeschlagen.",
  cow_akara_approach_failed: "Akara konnte über die aufgezeichneten Stadtkanten nicht sicher erreicht werden.",
  cow_akara_interaction_failed: "Akara konnte nicht sicher geöffnet werden.",
  cow_tome_shop_failed: "Akaras Handelsfenster konnte nicht sicher bestätigt werden.",
  cow_tome_purchase_failed: "Das zusätzliche Stadtportalbuch konnte nicht einzeln gekauft werden.",
  cow_tome_purchase_ambiguous: "Der Kauf erzeugte nicht genau eine neue Buch-UnitID.",
  cow_operational_tome_changed: "Das vorhandene Rückkehrbuch blieb beim Kauf nicht unverändert erhalten.",
  cow_tome_state_invalid: "Der Buchkauf konnte nicht aus einem stabilen Spielzustand fortgesetzt werden.",
  cow_tome_shop_close_failed: "Akaras Handelsfenster konnte nicht sicher geschlossen werden.",
  cow_portal_recipe_timeout: "Das Kuhportal-Rezept wurde nicht rechtzeitig sicher abgeschlossen.",
  cow_recipe_binding_invalid: "Die für das Rezept gebundenen Gegenstände sind nicht mehr eindeutig.",
  cow_recipe_binding_changed: "Eine gebundene Rezeptzutat hat sich während des Ablaufs geändert.",
  cow_recipe_bound_item_invalid: "Eine gebundene Rezeptzutat befindet sich nicht mehr am erwarteten Ort.",
  cow_recipe_initial_state_invalid: "Inventar und Würfel sind vor dem Rezept nicht in einem sicheren Ausgangszustand.",
  cow_recipe_state_invalid: "Der Rezeptablauf konnte wegen eines ungültigen Spielzustands nicht fortgesetzt werden.",
  cow_inventory_open_failed: "Das Inventar konnte für das Kuhportal-Rezept nicht sicher geöffnet werden.",
  cow_inventory_open_input_failed: "Der Eingabebefehl zum Öffnen des Inventars ist fehlgeschlagen.",
  cow_inventory_closed_before_cube: "Das Inventar wurde geschlossen, bevor der Würfel sicher geöffnet war.",
  cow_cube_open_input_failed: "Der Horadrimwürfel konnte nicht geöffnet werden.",
  cow_cube_open_unconfirmed: "Der geöffnete Horadrimwürfel wurde nicht bestätigt.",
  cow_cube_ui_unavailable: "Die Würfeloberfläche ist für das Rezept nicht verfügbar.",
  cow_cube_ui_revoked: "Die bestätigte Würfeloberfläche ging während des Rezepts verloren.",
  cow_recipe_transfer_input_failed: "Eine Rezeptzutat konnte nicht sicher in den Würfel verschoben werden.",
  cow_recipe_transfer_state_invalid: "Der Zustand einer Rezeptzutat änderte sich während des Transfers unerwartet.",
  cow_recipe_transfer_unconfirmed: "Der Transfer beider Rezeptzutaten wurde nicht bestätigt.",
  cow_recipe_contents_invalid: "Der Würfel enthält vor dem Transmutieren nicht exakt das gebundene Bein und Buch.",
  cow_transmute_repeat_blocked: "Ein unsicherer zweiter Transmutieren-Versuch wurde verhindert.",
  cow_transmute_focus_failed: "Das Spielfenster war vor dem Transmutieren nicht sicher fokussiert.",
  cow_transmute_input_failed: "Der Transmutieren-Klick konnte nicht sicher gesendet werden.",
  cow_recipe_resolution_invalid: "Das Rezept konnte nach dem Transmutieren nicht eindeutig ausgewertet werden.",
  cow_recipe_result_state_invalid: "Der Spielzustand nach dem Transmutieren ist ungültig.",
  cow_recipe_partial_consumption: "Nur ein Teil der gebundenen Rezeptzutaten wurde verbraucht.",
  cow_recipe_result_unconfirmed: "Der Verbrauch beider Rezeptzutaten wurde nicht bestätigt.",
  cow_portal_state_invalid: "Das neue Kuhportal konnte aus dem aktuellen Spielzustand nicht sicher ausgewertet werden.",
  cow_portal_ambiguous: "Mehr als ein mögliches neues Kuhportal wurde gefunden.",
  cow_portal_missing_after_consumption: "Die Zutaten wurden verbraucht, aber kein neues Kuhportal erschien.",
  cow_recipe_ui_close_failed: "Würfel und Inventar konnten nach dem Rezept nicht sicher geschlossen werden.",
  cow_portal_binding_lost: "Das gebundene Kuhportal ging vor dem Eintritt verloren.",
  cow_portal_entry_input_failed: "Der Eintritt in das gebundene Kuhportal konnte nicht gesendet werden.",
  cow_portal_entry_unconfirmed: "Der Eintritt in das Kuhportal wurde nicht durch die Moo Moo Farm bestätigt.",
  cow_portal_not_found: "Das gebundene Kuhportal wurde beim Eintritt nicht mehr gefunden.",
  cow_portal_too_far: "Das gebundene Kuhportal liegt außerhalb der sicheren Interaktionsdistanz.",
  cow_portal_hover_not_found: "Das gebundene Kuhportal wurde unter dem Mauszeiger nicht bestätigt.",
  cow_portal_projection_failed: "Das gebundene Kuhportal konnte nicht sicher auf das Spielfenster projiziert werden.",
  cow_portal_input_error: "Der Portal-Eingabebefehl ist fehlgeschlagen.",
  cow_ce_back_to_back: "Ein Corpse-Explosion-Folgecast ohne frischen Snapshot wurde verhindert.",
  cow_combat_not_wired: "Die Cow-Kampfsteuerung ist nicht vollständig verfügbar.",
  cow_combat_no_progress: "Der Cow-Kampf erzielte innerhalb des Sicherheitsfensters keinen bestätigten Fortschritt.",
  boss_combat_no_progress: "Der Hammerdin-Kampf erzielte innerhalb des Sicherheitsfensters keinen bestätigten Fortschritt.",
  cow_rejuvenation_reserve_missing: "Für den Cow-Run fehlt mindestens ein verwendbarer Regenerationstrank in der vorgesehenen Gürtelspalte.",
  cow_belt_layout_unseeded: "Für den Cow-Run fehlen korrekt belegte Heil- oder Manatrank-Gürtelspalten.",
  mercenary_died_during_run: "Der Söldner ist gestorben. Der Angriff wurde gestoppt und der Versuch wird nach sicherer Rückkehr neu gestartet.",
  combat_resource_exhausted: "Ein benötigter Trank ist aufgebraucht. Der Angriff wurde gestoppt und der Versuch wird kontrolliert beendet.",
  profile_required_skills_missing: "Dem Charakter fehlen Pflichtskills für das Kampfprofil. Die Queue wurde beendet.",
  profile_skills_read_unavailable: "Die Fähigkeiten des Charakters konnten nicht sicher geprüft werden. Die Queue wurde beendet.",
};

/** runResultReasonText translates stable Core reasons into concise operator help. */
export function runResultReasonText(reason: string): string {
  if (reason.startsWith("cow_tome_shop_close_failed:")) {
    return messages.cow_tome_shop_close_failed;
  }
  return messages[reason] ?? reason;
}
