schema_version: 1
revision: 1
id: tal-rasha
name: Tal Rasha's Wrappings
rules:
  - id: fine-spun-cloth
    action: keep
    expression: '[setitem] == "Tal Rasha''s Fire-Spun Cloth"'
  - id: adjudication
    action: keep
    expression: '[setitem] == "Tal Rasha''s Adjudication"'
  - id: lidless-eye
    action: keep
    expression: '[setitem] == "Tal Rasha''s Lidless Eye"'
  - id: guardianship
    action: keep
    expression: '[setitem] == "Tal Rasha''s Howling Wind"'
  - id: horadric-crest
    action: keep
    expression: '[setitem] == "Tal Rasha''s Horadric Crest"'
